// packages/angular/plugins/zoom/index.ts
import { NgTemplateOutlet } from '@angular/common';
import {
    ChangeDetectionStrategy,
    Component,
    computed,
    DestroyRef,
    effect,
    ElementRef,
    inject,
    Injectable,
    input,
    signal,
    untracked,
    viewChild,
    type TemplateRef,
} from '@angular/core';
import {
    applyZoom,
    clampPan,
    clampScale,
    getActualSizeScale,
    getPanBounds,
    getPanMomentum,
    getPinchScale,
    getPointerDistance,
    getPointZoomPan,
    getWindowedVelocity,
    pushVelocitySample,
    getSlideType,
    initialZoomSlice,
    type VelocitySample,
    type ZoomPan,
    type ZoomSlice,
} from '@lightgallery/headless';
import {
    LG_FEATURE_INIT,
    LG_PLUGIN_CONTEXT,
    type LgFeature,
    type LgGalleryItem,
} from '@lightgallery/angular';

/**
 * Zoom feature (2.x `lg-zoom`): toolbar buttons, double-click/tap point
 * zoom, pinch, pan-when-zoomed — the gesture-consumer template wave 2
 * copies. Same performance contract as the core gestures:
 * pinch/pan write transforms straight to the DOM; signals change only on
 * discrete commits (button step, gesture end).
 *
 * DOM deviation vs 2.x (noted for the 007 parity matrix, same as React):
 * transforms live on two plugin-owned wrapper divs with inline transitions
 * instead of `.lg-img-wrap`/`.lg-image` + `lg-zoomable` CSS.
 */

export interface ZoomStrings {
    zoomIn: string;
    zoomOut: string;
    viewActualSize: string;
}

export interface ZoomSettings {
    /** Zoom increment per zoom-in/out step. */
    scale: number;
    /** Enable/disable the feature. */
    zoom: boolean;
    /** Allow zooming beyond the image's actual size. */
    infiniteZoom: boolean;
    /** Show the actual-size button. */
    actualSize: boolean;
    /** Show zoom in/out buttons. */
    showZoomInOutIcons: boolean;
    /** Icon classes for the zoom in/out buttons. */
    actualSizeIcons: {
        zoomIn: 'lg-zoom-in' | 'lg-actual-size';
        zoomOut: 'lg-zoom-out' | 'lg-actual-size';
    };
    /** Delay (ms) after a slide loads before zoom interactions arm. */
    enableZoomAfter: number;
    zoomPluginStrings: ZoomStrings;
}

export const zoomSettings: ZoomSettings = {
    scale: 1,
    zoom: true,
    infiniteZoom: true,
    actualSize: true,
    showZoomInOutIcons: false,
    actualSizeIcons: {
        zoomIn: 'lg-zoom-in',
        zoomOut: 'lg-zoom-out',
    },
    enableZoomAfter: 300,
    zoomPluginStrings: {
        zoomIn: 'Zoom in',
        zoomOut: 'Zoom out',
        viewActualSize: 'View actual size',
    },
};

const ZOOM_IN_EVENT = 'lg-zoom-in';
const ZOOM_OUT_EVENT = 'lg-zoom-out';
const ACTUAL_SIZE_EVENT = 'lg-actual-size';
const ZOOM_TRANSITION = 'transform 0.3s cubic-bezier(0, 0, 0.25, 1)';
/** 2.x post-gesture settle ease (`lg-zoom-drag-transition`). */
const SETTLE_TRANSITION = 'transform 0.8s cubic-bezier(0, 0, 0.25, 1)';

function isImageTarget(target: unknown): boolean {
    return (
        target instanceof HTMLElement && target.classList.contains('lg-image')
    );
}

type ZoomResolved = ZoomSettings & Record<string, unknown>;

@Component({
    selector: 'lg-zoom-toolbar',
    changeDetection: ChangeDetectionStrategy.OnPush,
    template: `
        @if (settings().zoom) { @if (settings().showZoomInOutIcons) {
        <button
            type="button"
            [attr.aria-label]="settings().zoomPluginStrings.zoomIn"
            [class]="settings().actualSizeIcons.zoomIn + ' lg-icon'"
            (click)="emit(ZOOM_IN)"
        ></button>
        <button
            type="button"
            [attr.aria-label]="settings().zoomPluginStrings.zoomOut"
            [class]="settings().actualSizeIcons.zoomOut + ' lg-icon'"
            (click)="emit(ZOOM_OUT)"
        ></button>
        } @if (settings().actualSize) {
        <button
            type="button"
            [attr.aria-label]="settings().zoomPluginStrings.viewActualSize"
            class="lg-actual-size lg-icon"
            (click)="emit(ACTUAL)"
        ></button>
        } }
    `,
})
export class LgZoomToolbarComponent {
    private readonly ctx = inject(LG_PLUGIN_CONTEXT);
    protected readonly settings = computed(
        () => this.ctx.settings() as unknown as ZoomResolved,
    );
    protected readonly ZOOM_IN = ZOOM_IN_EVENT;
    protected readonly ZOOM_OUT = ZOOM_OUT_EVENT;
    protected readonly ACTUAL = ACTUAL_SIZE_EVENT;

    protected emit(name: string): void {
        this.ctx.events.emit(name, undefined);
    }
}

@Component({
    selector: 'lg-zoom-wrapper',
    changeDetection: ChangeDetectionStrategy.OnPush,
    imports: [NgTemplateOutlet],
    template: `
        @if (enabled()) {
        <div
            #panEl
            class="lg-zoom-pan"
            [style.position]="'absolute'"
            [style.inset]="'0'"
            [style.transform]="panTransform()"
            [style.transition]="transition()"
            (pointerdown)="onPointerDown($event)"
            (dblclick)="onDoubleClick($event)"
        >
            <div
                #scaleEl
                class="lg-zoom-scale"
                [style.position]="'absolute'"
                [style.inset]="'0'"
                [style.transform]="scaleTransform()"
                [style.transform-origin]="'center center'"
                [style.transition]="transition()"
            >
                <ng-container [ngTemplateOutlet]="content()" />
            </div>
        </div>
        } @else {
        <ng-container [ngTemplateOutlet]="content()" />
        }
    `,
})
export class LgZoomWrapperComponent {
    readonly item = input.required<LgGalleryItem>();
    readonly index = input.required<number>();
    readonly isCurrent = input(false);
    readonly content = input.required<TemplateRef<unknown>>();

    private readonly ctx = inject(LG_PLUGIN_CONTEXT);
    protected readonly settings = computed(
        () => this.ctx.settings() as unknown as ZoomResolved,
    );
    protected readonly enabled = computed(
        () => this.settings().zoom && getSlideType(this.item()) === 'image',
    );

    private readonly panEl = viewChild<ElementRef<HTMLDivElement>>('panEl');
    private readonly scaleEl = viewChild<ElementRef<HTMLDivElement>>('scaleEl');

    private readonly transitionMode = signal<'default' | 'settle'>('default');
    protected readonly transition = computed(() =>
        this.transitionMode() === 'settle'
            ? SETTLE_TRANSITION
            : ZOOM_TRANSITION,
    );

    /** Committed zoom slice; live pinch/pan bypasses it (direct writes). */
    private readonly zoom = signal<ZoomSlice>(initialZoomSlice);
    protected readonly panTransform = computed(
        () => `translate3d(${this.zoom().pan.x}px, ${this.zoom().pan.y}px, 0)`,
    );
    protected readonly scaleTransform = computed(
        () => `scale3d(${this.zoom().scale}, ${this.zoom().scale}, 1)`,
    );

    private readonly interactive = signal(false);
    private live: ZoomSlice = initialZoomSlice;
    private readonly pointers = new Map<number, ZoomPan>();
    private pinch: {
        startDistance: number;
        startScale: number;
        startPan: ZoomPan;
        startMid: ZoomPan;
    } | null = null;
    private panDrag: {
        pointerId: number;
        startX: number;
        startY: number;
        samples: VelocitySample[];
        startPan: ZoomPan;
    } | null = null;
    private detachWindow: (() => void) | null = null;
    private lastTap = 0;
    private armTimer: ReturnType<typeof setTimeout> | null = null;

    /** Narrow: re-run the arm effect only when THIS slide's flag flips. */
    private readonly loaded = computed(() =>
        this.ctx.state().loadedSlides.has(this.index()),
    );

    constructor() {
        // Zoom interactions arm `enableZoomAfter` ms after the slide loads.
        effect((onCleanup) => {
            const loaded = this.loaded();
            const enabled = this.enabled();
            if (!loaded || !enabled) {
                this.interactive.set(false);
                return;
            }
            this.armTimer = setTimeout(
                () => this.interactive.set(true),
                untracked(this.settings).enableZoomAfter,
            );
            onCleanup(() => {
                if (this.armTimer !== null) {
                    clearTimeout(this.armTimer);
                    this.armTimer = null;
                }
            });
        });
        // Toolbar buttons drive the current slide's wrapper via the bus.
        effect((onCleanup) => {
            if (!this.isCurrent() || !this.enabled()) {
                return;
            }
            const offs = [
                this.ctx.events.on(ZOOM_IN_EVENT, () =>
                    this.stepZoom(untracked(this.settings).scale),
                ),
                this.ctx.events.on(ZOOM_OUT_EVENT, () =>
                    this.stepZoom(-untracked(this.settings).scale),
                ),
                this.ctx.events.on(ACTUAL_SIZE_EVENT, () =>
                    this.toggleActualSize({ x: 0, y: 0 }),
                ),
            ];
            onCleanup(() => offs.forEach((off) => off()));
        });
        // Reset when the slide stops being current (2.x parity).
        effect(() => {
            if (!this.isCurrent()) {
                untracked(() => this.reset());
            }
        });
        inject(DestroyRef).onDestroy(() => {
            this.detachWindow?.();
            if (this.live.zoomed) {
                this.ctx.layout.setOuterClass('lg-zoomed', false);
                this.ctx.gestureLock.claim(null);
            }
        });
    }

    private measure(): {
        imageWidth: number;
        imageHeight: number;
        naturalWidth: number;
        containerWidth: number;
        containerHeight: number;
    } {
        const img = this.scaleEl()?.nativeElement.querySelector('img');
        const slide =
            this.panEl()?.nativeElement.closest<HTMLElement>('.lg-item');
        return {
            imageWidth: img?.offsetWidth ?? 0,
            imageHeight: img?.offsetHeight ?? 0,
            naturalWidth: img?.naturalWidth ?? 0,
            containerWidth: slide?.offsetWidth ?? 0,
            containerHeight: slide?.offsetHeight ?? 0,
        };
    }

    private maxScale(): number {
        const { naturalWidth, imageWidth } = this.measure();
        return getActualSizeScale(naturalWidth, imageWidth);
    }

    private setLiveTransition(value: string): void {
        const pan = this.panEl()?.nativeElement;
        if (pan) {
            pan.style.transition = value;
        }
        const scaleEl = this.scaleEl()?.nativeElement;
        if (scaleEl) {
            scaleEl.style.transition = value;
        }
    }

    /** Live transforms during pinch/pan — direct DOM writes, zero CD. */
    private applyLive(slice: ZoomSlice): void {
        this.live = slice;
        const pan = this.panEl()?.nativeElement;
        if (pan) {
            pan.style.transform = `translate3d(${slice.pan.x}px, ${slice.pan.y}px, 0)`;
        }
        const scaleEl = this.scaleEl()?.nativeElement;
        if (scaleEl) {
            scaleEl.style.transform = `scale3d(${slice.scale}, ${slice.scale}, 1)`;
        }
    }

    private commit(
        scale: number,
        pan: ZoomPan,
        mode: 'default' | 'settle' = 'default',
    ): void {
        this.transitionMode.set(mode);
        this.setLiveTransition(
            mode === 'settle' ? SETTLE_TRANSITION : ZOOM_TRANSITION,
        );
        const cfg = untracked(this.settings);
        const max = this.maxScale();
        const clamped = clampScale(scale, max, cfg.infiniteZoom);
        const { imageWidth, imageHeight, containerWidth, containerHeight } =
            this.measure();
        const bounds = getPanBounds(
            imageWidth,
            imageHeight,
            containerWidth,
            containerHeight,
            clamped,
        );
        const next = applyZoom(
            this.live,
            clamped,
            clampPan(pan, bounds),
            max,
            cfg.infiniteZoom,
        );
        // Write the committed transforms inline immediately (no flash while
        // CD is pending); the signal keeps the bindings in agreement so any
        // later binding write lands on the same values.
        this.applyLive(next);
        this.zoom.set(next);
        this.ctx.layout.setOuterClass('lg-zoomed', next.zoomed);
        // Core swipe stands down while zoomed (2.x `touchAction`).
        this.ctx.gestureLock.claim(next.zoomed ? 'zoomSwipe' : null);
    }

    private reset(): void {
        this.transitionMode.set('default');
        this.setLiveTransition(ZOOM_TRANSITION);
        this.pointers.clear();
        this.pinch = null;
        this.panDrag = null;
        this.detachWindow?.();
        this.detachWindow = null;
        this.live = initialZoomSlice;
        this.zoom.set(initialZoomSlice);
        this.ctx.layout.setOuterClass('lg-zoomed', false);
        this.ctx.gestureLock.claim(null);
    }

    private stepZoom(delta: number): void {
        const previous = this.live;
        const target = clampScale(
            previous.scale + delta,
            this.maxScale(),
            untracked(this.settings).infiniteZoom,
        );
        // Zoom about the center: the pan scales with the ratio.
        const pan = getPointZoomPan(
            { x: 0, y: 0 },
            previous.pan,
            previous.scale,
            target,
        );
        this.commit(target, pan);
    }

    private toggleActualSize(point: ZoomPan): void {
        const previous = this.live;
        if (previous.zoomed) {
            this.commit(1, { x: 0, y: 0 });
            return;
        }
        const target = clampScale(this.maxScale(), this.maxScale(), true);
        this.commit(
            target,
            getPointZoomPan(point, previous.pan, previous.scale, target),
        );
    }

    private eventPoint(event: { clientX: number; clientY: number }): ZoomPan {
        const slide =
            this.panEl()?.nativeElement.closest<HTMLElement>('.lg-item');
        const rect = slide?.getBoundingClientRect();
        if (!rect) {
            return { x: 0, y: 0 };
        }
        return {
            x: event.clientX - (rect.left + rect.width / 2),
            y: event.clientY - (rect.top + rect.height / 2),
        };
    }

    private attachWindowListeners(): void {
        if (this.detachWindow) {
            return;
        }
        const onMove = (event: PointerEvent): void => {
            if (!this.pointers.has(event.pointerId)) {
                return;
            }
            this.pointers.set(event.pointerId, {
                x: event.clientX,
                y: event.clientY,
            });
            const pinch = this.pinch;
            if (pinch && this.pointers.size >= 2) {
                const [a, b] = [...this.pointers.values()];
                const scale = getPinchScale(
                    pinch.startDistance,
                    getPointerDistance(a!, b!),
                    pinch.startScale,
                    this.maxScale(),
                    untracked(this.settings).infiniteZoom,
                );
                // Anchor the zoom to the pinch's starting midpoint (2.x
                // anchored to the first finger; the midpoint is the same
                // idea without finger-order dependence).
                const pan = getPointZoomPan(
                    pinch.startMid,
                    pinch.startPan,
                    pinch.startScale,
                    scale,
                );
                this.applyLive({
                    ...this.live,
                    scale,
                    pan,
                    zoomed: scale > 1,
                });
                return;
            }
            const drag = this.panDrag;
            if (drag && event.pointerId === drag.pointerId) {
                drag.samples = pushVelocitySample(drag.samples, {
                    x: event.clientX,
                    y: event.clientY,
                    t: Date.now(),
                });
                const {
                    imageWidth,
                    imageHeight,
                    containerWidth,
                    containerHeight,
                } = this.measure();
                const bounds = getPanBounds(
                    imageWidth,
                    imageHeight,
                    containerWidth,
                    containerHeight,
                    this.live.scale,
                );
                const pan = clampPan(
                    {
                        x: drag.startPan.x + (event.clientX - drag.startX),
                        y: drag.startPan.y + (event.clientY - drag.startY),
                    },
                    bounds,
                );
                this.applyLive({ ...this.live, pan });
            }
        };
        const onUp = (event: PointerEvent): void => {
            if (!this.pointers.has(event.pointerId)) {
                return;
            }
            this.pointers.delete(event.pointerId);
            const endedPinch = this.pinch;
            if (endedPinch && this.pointers.size < 2) {
                this.pinch = null;
                // Pinch release snaps into [1, actual size] regardless of
                // infiniteZoom (2.x pinch touchend rule — the setting
                // governs button zoom only). The pan is recomputed through
                // the same focal anchor so the snap stays centered on the
                // pinched point.
                const target = clampScale(
                    this.live.scale,
                    this.maxScale(),
                    false,
                );
                this.commit(
                    target,
                    getPointZoomPan(
                        endedPinch.startMid,
                        endedPinch.startPan,
                        endedPinch.startScale,
                        target,
                    ),
                    'settle',
                );
            }
            const drag = this.panDrag;
            if (drag && event.pointerId === drag.pointerId) {
                this.panDrag = null;
                let pan = this.live.pan;
                if (event.type === 'pointerup') {
                    // 2.x `touchendZoom` momentum: a fast release keeps
                    // traveling in proportion to its speed, anchored at the
                    // gesture-start pan; commit clamps the projection into
                    // bounds. A canceled pointer settles where it is.
                    const projected = getPanMomentum(
                        {
                            x: event.clientX - drag.startX,
                            y: event.clientY - drag.startY,
                        },
                        getWindowedVelocity(drag.samples, Date.now()),
                    );
                    pan = {
                        x: drag.startPan.x + projected.x,
                        y: drag.startPan.y + projected.y,
                    };
                }
                this.commit(this.live.scale, pan, 'settle');
            }
            if (this.pointers.size === 0) {
                this.detachWindow?.();
                this.detachWindow = null;
            }
        };
        window.addEventListener('pointermove', onMove, { passive: true });
        window.addEventListener('pointerup', onUp);
        window.addEventListener('pointercancel', onUp);
        this.detachWindow = () => {
            window.removeEventListener('pointermove', onMove);
            window.removeEventListener('pointerup', onUp);
            window.removeEventListener('pointercancel', onUp);
        };
    }

    protected onPointerDown(event: PointerEvent): void {
        if (!this.enabled() || !this.interactive() || !this.isCurrent()) {
            return;
        }
        this.pointers.set(event.pointerId, {
            x: event.clientX,
            y: event.clientY,
        });
        // Every insert gets its removal path: onUp/onCancel must be live
        // for this pointer or the ledger leaks a phantom that corrupts
        // the next gesture.
        this.attachWindowListeners();

        if (this.pointers.size === 2 && event.pointerType === 'touch') {
            const [a, b] = [...this.pointers.values()];
            this.pinch = {
                startDistance: getPointerDistance(a!, b!),
                startScale: this.live.scale,
                startPan: this.live.pan,
                startMid: this.eventPoint({
                    clientX: (a!.x + b!.x) / 2,
                    clientY: (a!.y + b!.y) / 2,
                }),
            };
            this.panDrag = null;
            this.ctx.gestureLock.claim('pinch');
            this.setLiveTransition('none');
            return;
        }

        // Double-tap detection for touch (mouse uses dblclick), gated to
        // the image itself (2.x `hasClass('lg-image')`).
        if (
            event.pointerType === 'touch' &&
            this.pointers.size === 1 &&
            isImageTarget(event.target)
        ) {
            const now = Date.now();
            if (now - this.lastTap < 300) {
                this.lastTap = 0;
                this.toggleActualSize(this.eventPoint(event));
                return;
            }
            this.lastTap = now;
        }

        if (this.live.zoomed && this.pointers.size === 1) {
            event.stopPropagation();
            this.panDrag = {
                pointerId: event.pointerId,
                startX: event.clientX,
                startY: event.clientY,
                samples: [
                    { x: event.clientX, y: event.clientY, t: Date.now() },
                ],
                startPan: this.live.pan,
            };
            this.setLiveTransition('none');
        }
    }

    protected onDoubleClick(event: MouseEvent): void {
        if (!this.enabled() || !this.interactive() || !this.isCurrent()) {
            return;
        }
        if (!isImageTarget(event.target)) {
            return;
        }
        this.toggleActualSize(this.eventPoint(event));
    }
}

/**
 * `lg-use-transition-for-zoom` while registered (React `usePlugin`
 * twin). Decorative in v3 (transitions are inline on the zoom wrappers;
 * 2.x CSS targeted .lg-img-wrap/.lg-image) — kept as a public CSS hook
 * so consumer stylesheets can target zoom-enabled galleries.
 */
@Injectable()
export class LgZoomInitService {
    constructor() {
        const ctx = inject(LG_PLUGIN_CONTEXT);
        effect((onCleanup) => {
            const enabled = !!(ctx.settings() as { zoom?: boolean }).zoom;
            ctx.layout.setOuterClass('lg-use-transition-for-zoom', enabled);
            onCleanup(() =>
                ctx.layout.setOuterClass('lg-use-transition-for-zoom', false),
            );
        });
    }
}

export function withZoom(
    options: Partial<ZoomSettings> = {},
): LgFeature<ZoomSettings> {
    return {
        name: 'zoom',
        defaults: zoomSettings,
        options,
        slots: {
            toolbar: LgZoomToolbarComponent,
            slideWrapper: LgZoomWrapperComponent,
        },
        providers: [
            LgZoomInitService,
            {
                provide: LG_FEATURE_INIT,
                useExisting: LgZoomInitService,
                multi: true,
            },
        ],
    };
}

// packages/react/src/plugins/zoom/index.tsx
import {
    useEffect,
    useRef,
    useState,
    type MouseEvent as ReactMouseEvent,
    type PointerEvent as ReactPointerEvent,
    type ReactElement,
} from 'react';
import {
    applyZoom,
    clampPan,
    clampScale,
    getActualSizeScale,
    getPanBounds,
    getPanMomentum,
    getPinchScale,
    getPointerDistance,
    getPointZoomPan,
    getWindowedVelocity,
    pushVelocitySample,
    getSlideType,
    initialZoomSlice,
    type VelocitySample,
    type ZoomPan,
    type ZoomSlice,
} from '@lightgallery/headless';

import { useGalleryInternal, useGalleryState } from '../../context';
import { usePluginSettings } from '../runtime';
import type { LgPlugin, PluginContext, SlideWrapperProps } from '../types';

/**
 * Zoom plugin (2.x `lg-zoom`): toolbar buttons, double-click/tap point
 * zoom, pinch, pan-when-zoomed. Same performance contract as the core
 * gestures: pinch/pan write transforms straight to the DOM;
 * React state changes only on discrete commits (button step, gesture end).
 *
 * DOM deviation vs 2.x (noted in the parity matrix): transforms live
 * on two plugin-owned wrapper divs with inline transitions instead of
 * `.lg-img-wrap`/`.lg-image` + `lg-zoomable` CSS.
 */

export interface ZoomStrings {
    zoomIn: string;
    zoomOut: string;
    viewActualSize: string;
}

export interface ZoomSettings {
    /** Zoom increment per zoom-in/out step. */
    scale: number;
    /** Enable/disable the plugin. */
    zoom: boolean;
    /** Allow zooming beyond the image's actual size. */
    infiniteZoom: boolean;
    /** Show the actual-size button. */
    actualSize: boolean;
    /** Show zoom in/out buttons. */
    showZoomInOutIcons: boolean;
    /** Icon classes for the zoom in/out buttons. */
    actualSizeIcons: {
        zoomIn: 'lg-zoom-in' | 'lg-actual-size';
        zoomOut: 'lg-zoom-out' | 'lg-actual-size';
    };
    /** Delay (ms) after a slide loads before zoom interactions arm. */
    enableZoomAfter: number;
    zoomPluginStrings: ZoomStrings;
}

export const zoomSettings: ZoomSettings = {
    scale: 1,
    zoom: true,
    infiniteZoom: true,
    actualSize: true,
    showZoomInOutIcons: false,
    actualSizeIcons: {
        zoomIn: 'lg-zoom-in',
        zoomOut: 'lg-zoom-out',
    },
    enableZoomAfter: 300,
    zoomPluginStrings: {
        zoomIn: 'Zoom in',
        zoomOut: 'Zoom out',
        viewActualSize: 'View actual size',
    },
};

const TRANSITION = 'transform 0.3s cubic-bezier(0, 0, 0.25, 1)';
/** 2.x post-gesture settle ease (`lg-zoom-drag-transition`). */
const SETTLE_TRANSITION = 'transform 0.8s cubic-bezier(0, 0, 0.25, 1)';

function isImageTarget(target: unknown): boolean {
    return (
        target instanceof HTMLElement && target.classList.contains('lg-image')
    );
}

const ZOOM_IN_EVENT = 'lg-zoom-in';
const ZOOM_OUT_EVENT = 'lg-zoom-out';
const ACTUAL_SIZE_EVENT = 'lg-actual-size';

function ZoomToolbar(): ReactElement | null {
    const internal = useGalleryInternal();
    const settings = usePluginSettings<ZoomSettings>();
    if (!settings.zoom) {
        return null;
    }
    const emit = (name: string) => internal.events.emit(name, undefined);
    return (
        <>
            {settings.showZoomInOutIcons && (
                <button
                    type="button"
                    aria-label={settings.zoomPluginStrings.zoomIn}
                    className={`${settings.actualSizeIcons.zoomIn} lg-icon`}
                    onClick={() => emit(ZOOM_IN_EVENT)}
                />
            )}
            {settings.showZoomInOutIcons && (
                <button
                    type="button"
                    aria-label={settings.zoomPluginStrings.zoomOut}
                    className={`${settings.actualSizeIcons.zoomOut} lg-icon`}
                    onClick={() => emit(ZOOM_OUT_EVENT)}
                />
            )}
            {settings.actualSize && (
                <button
                    type="button"
                    aria-label={settings.zoomPluginStrings.viewActualSize}
                    className="lg-actual-size lg-icon"
                    onClick={() => emit(ACTUAL_SIZE_EVENT)}
                />
            )}
        </>
    );
}

function ZoomWrapper({
    item,
    index,
    isCurrent,
    children,
}: SlideWrapperProps): ReactElement {
    const state = useGalleryState();
    const internal = useGalleryInternal();
    const settings = usePluginSettings<ZoomSettings>();
    const enabled = settings.zoom && getSlideType(item) === 'image';

    const [zoom, setZoom] = useState<ZoomSlice>(initialZoomSlice);
    const [interactive, setInteractive] = useState(false);
    // 2.x transition choreography: default ease for button/double-tap
    // zoom, none while a pinch/pan tracks the fingers, a longer settle
    // ease for the release snap.
    const [transitionMode, setTransitionMode] = useState<'default' | 'settle'>(
        'default',
    );
    const panRef = useRef<HTMLDivElement>(null);
    const scaleElRef = useRef<HTMLDivElement>(null);
    const liveRef = useRef<ZoomSlice>(initialZoomSlice);
    const settingsRef = useRef(settings);
    settingsRef.current = settings;
    const pointersRef = useRef(new Map<number, ZoomPan>());
    const pinchRef = useRef<{
        startDistance: number;
        startScale: number;
        startPan: ZoomPan;
        startMid: ZoomPan;
    } | null>(null);
    const panDragRef = useRef<{
        pointerId: number;
        startX: number;
        startY: number;
        samples: VelocitySample[];
        startPan: ZoomPan;
        moved: boolean;
    } | null>(null);
    const detachRef = useRef<(() => void) | null>(null);
    const lastTapRef = useRef(0);

    const measure = () => {
        const img = scaleElRef.current?.querySelector('img');
        const slide = panRef.current?.closest<HTMLElement>('.lg-item');
        return {
            imageWidth: img?.offsetWidth ?? 0,
            imageHeight: img?.offsetHeight ?? 0,
            naturalWidth: img?.naturalWidth ?? 0,
            containerWidth: slide?.offsetWidth ?? 0,
            containerHeight: slide?.offsetHeight ?? 0,
        };
    };

    const maxScale = () => {
        const { naturalWidth, imageWidth } = measure();
        return getActualSizeScale(naturalWidth, imageWidth);
    };

    const setLiveTransition = (value: string) => {
        if (panRef.current) {
            panRef.current.style.transition = value;
        }
        if (scaleElRef.current) {
            scaleElRef.current.style.transition = value;
        }
    };

    const applyLive = (slice: ZoomSlice) => {
        liveRef.current = slice;
        if (panRef.current) {
            panRef.current.style.transform = `translate3d(${slice.pan.x}px, ${slice.pan.y}px, 0)`;
        }
        if (scaleElRef.current) {
            scaleElRef.current.style.transform = `scale3d(${slice.scale}, ${slice.scale}, 1)`;
        }
    };

    const commit = (
        scale: number,
        pan: ZoomPan,
        mode: 'default' | 'settle' = 'default',
    ) => {
        setTransitionMode(mode);
        setLiveTransition(mode === 'settle' ? SETTLE_TRANSITION : TRANSITION);
        const cfg = settingsRef.current;
        const max = maxScale();
        const clamped = clampScale(scale, max, cfg.infiniteZoom);
        const { imageWidth, imageHeight, containerWidth, containerHeight } =
            measure();
        const bounds = getPanBounds(
            imageWidth,
            imageHeight,
            containerWidth,
            containerHeight,
            clamped,
        );
        const next = applyZoom(
            liveRef.current,
            clamped,
            clampPan(pan, bounds),
            max,
            cfg.infiniteZoom,
        );
        // Inline styles first — React's style diffing compares against
        // its own last render, not the live writes, so a commit that
        // matches the previous committed state would otherwise skip the
        // DOM write and strand the gesture's last live transform.
        applyLive(next);
        setZoom(next);
        internal.layout.setOuterClass('lg-zoomed', next.zoomed);
        // Core swipe stands down while zoomed (2.x `touchAction`).
        internal.gestureSeam.claim(next.zoomed ? 'zoomSwipe' : null);
    };

    const reset = () => {
        setTransitionMode('default');
        setLiveTransition(TRANSITION);
        pointersRef.current.clear();
        pinchRef.current = null;
        panDragRef.current = null;
        detachRef.current?.();
        detachRef.current = null;
        liveRef.current = initialZoomSlice;
        setZoom(initialZoomSlice);
        internal.layout.setOuterClass('lg-zoomed', false);
        internal.gestureSeam.claim(null);
    };

    const stepZoom = (delta: number) => {
        const previous = liveRef.current;
        const target = clampScale(
            previous.scale + delta,
            maxScale(),
            settingsRef.current.infiniteZoom,
        );
        // Zoom about the center: the pan scales with the ratio.
        const pan = getPointZoomPan(
            { x: 0, y: 0 },
            previous.pan,
            previous.scale,
            target,
        );
        commit(target, pan);
    };

    const toggleActualSize = (point: ZoomPan) => {
        const previous = liveRef.current;
        if (previous.zoomed) {
            commit(1, { x: 0, y: 0 });
            return;
        }
        const target = clampScale(maxScale(), maxScale(), true);
        commit(
            target,
            getPointZoomPan(point, previous.pan, previous.scale, target),
        );
    };

    // Zoom interactions arm `enableZoomAfter` ms after the slide loads.
    const loaded = state.loadedSlides.has(index);
    useEffect(() => {
        if (!loaded || !enabled) {
            setInteractive(false);
            return;
        }
        const timer = window.setTimeout(
            () => setInteractive(true),
            settingsRef.current.enableZoomAfter,
        );
        return () => window.clearTimeout(timer);
    }, [loaded, enabled]);

    // Toolbar buttons drive the current slide's wrapper via the event bus.
    useEffect(() => {
        if (!isCurrent || !enabled) {
            return;
        }
        const offs = [
            internal.events.on(ZOOM_IN_EVENT, () =>
                stepZoom(settingsRef.current.scale),
            ),
            internal.events.on(ZOOM_OUT_EVENT, () =>
                stepZoom(-settingsRef.current.scale),
            ),
            internal.events.on(ACTUAL_SIZE_EVENT, () =>
                toggleActualSize({ x: 0, y: 0 }),
            ),
        ];
        return () => offs.forEach((off) => off());
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [isCurrent, enabled]);

    // Reset when the slide stops being current (2.x resets on slide change).
    useEffect(() => {
        if (!isCurrent) {
            reset();
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [isCurrent]);
    useEffect(
        () => () => {
            detachRef.current?.();
            if (liveRef.current.zoomed) {
                internal.layout.setOuterClass('lg-zoomed', false);
                internal.gestureSeam.claim(null);
            }
        },
        // eslint-disable-next-line react-hooks/exhaustive-deps
        [],
    );

    const eventPoint = (event: {
        clientX: number;
        clientY: number;
    }): ZoomPan => {
        const slide = panRef.current?.closest<HTMLElement>('.lg-item');
        const rect = slide?.getBoundingClientRect();
        if (!rect) {
            return { x: 0, y: 0 };
        }
        return {
            x: event.clientX - (rect.left + rect.width / 2),
            y: event.clientY - (rect.top + rect.height / 2),
        };
    };

    const attachWindowListeners = () => {
        if (detachRef.current) {
            return;
        }
        const onMove = (event: PointerEvent) => {
            const pointers = pointersRef.current;
            if (!pointers.has(event.pointerId)) {
                return;
            }
            pointers.set(event.pointerId, {
                x: event.clientX,
                y: event.clientY,
            });
            const pinch = pinchRef.current;
            if (pinch && pointers.size >= 2) {
                const [a, b] = [...pointers.values()];
                const scale = getPinchScale(
                    pinch.startDistance,
                    getPointerDistance(a!, b!),
                    pinch.startScale,
                    maxScale(),
                    settingsRef.current.infiniteZoom,
                );
                // Anchor the zoom to the pinch's starting midpoint (2.x
                // anchored to the first finger; the midpoint is the same
                // idea without the finger-order dependence).
                const pan = getPointZoomPan(
                    pinch.startMid,
                    pinch.startPan,
                    pinch.startScale,
                    scale,
                );
                applyLive({
                    ...liveRef.current,
                    scale,
                    pan,
                    zoomed: scale > 1,
                });
                return;
            }
            const drag = panDragRef.current;
            if (drag && event.pointerId === drag.pointerId) {
                drag.moved = true;
                drag.samples = pushVelocitySample(drag.samples, {
                    x: event.clientX,
                    y: event.clientY,
                    t: Date.now(),
                });
                const {
                    imageWidth,
                    imageHeight,
                    containerWidth,
                    containerHeight,
                } = measure();
                const bounds = getPanBounds(
                    imageWidth,
                    imageHeight,
                    containerWidth,
                    containerHeight,
                    liveRef.current.scale,
                );
                const pan = clampPan(
                    {
                        x: drag.startPan.x + (event.clientX - drag.startX),
                        y: drag.startPan.y + (event.clientY - drag.startY),
                    },
                    bounds,
                );
                applyLive({ ...liveRef.current, pan });
            }
        };
        const onUp = (event: PointerEvent) => {
            const pointers = pointersRef.current;
            if (!pointers.has(event.pointerId)) {
                return;
            }
            pointers.delete(event.pointerId);
            const pinch = pinchRef.current;
            if (pinch && pointers.size < 2) {
                pinchRef.current = null;
                // Pinch release snaps into [1, actual size] regardless of
                // infiniteZoom (2.x pinch touchend rule — the setting
                // governs button zoom only). The pan is recomputed through
                // the same focal anchor so the snap stays centered on the
                // pinched point instead of drifting.
                const target = clampScale(
                    liveRef.current.scale,
                    maxScale(),
                    false,
                );
                commit(
                    target,
                    getPointZoomPan(
                        pinch.startMid,
                        pinch.startPan,
                        pinch.startScale,
                        target,
                    ),
                    'settle',
                );
            }
            const drag = panDragRef.current;
            if (drag && event.pointerId === drag.pointerId) {
                panDragRef.current = null;
                let pan = liveRef.current.pan;
                if (event.type === 'pointerup') {
                    // 2.x `touchendZoom` momentum: a fast release keeps
                    // traveling in proportion to its speed, anchored at the
                    // gesture-start pan; commit clamps the projection into
                    // bounds. A canceled pointer settles where it is.
                    const projected = getPanMomentum(
                        {
                            x: event.clientX - drag.startX,
                            y: event.clientY - drag.startY,
                        },
                        getWindowedVelocity(drag.samples, Date.now()),
                    );
                    pan = {
                        x: drag.startPan.x + projected.x,
                        y: drag.startPan.y + projected.y,
                    };
                }
                commit(liveRef.current.scale, pan, 'settle');
            }
            if (pointers.size === 0) {
                detachRef.current?.();
                detachRef.current = null;
            }
        };
        window.addEventListener('pointermove', onMove, { passive: true });
        window.addEventListener('pointerup', onUp);
        window.addEventListener('pointercancel', onUp);
        detachRef.current = () => {
            window.removeEventListener('pointermove', onMove);
            window.removeEventListener('pointerup', onUp);
            window.removeEventListener('pointercancel', onUp);
        };
    };

    const onPointerDown = (event: ReactPointerEvent) => {
        if (!enabled || !interactive || !isCurrent) {
            return;
        }
        const pointers = pointersRef.current;
        pointers.set(event.pointerId, {
            x: event.clientX,
            y: event.clientY,
        });
        // Every insert gets its removal path: onUp/onCancel must be live
        // for this pointer or the ledger leaks a phantom that corrupts
        // the next gesture.
        attachWindowListeners();

        if (pointers.size === 2 && event.pointerType === 'touch') {
            const [a, b] = [...pointers.values()];
            pinchRef.current = {
                startDistance: getPointerDistance(a!, b!),
                startScale: liveRef.current.scale,
                startPan: liveRef.current.pan,
                startMid: eventPoint({
                    clientX: (a!.x + b!.x) / 2,
                    clientY: (a!.y + b!.y) / 2,
                }),
            };
            panDragRef.current = null;
            internal.gestureSeam.claim('pinch');
            setLiveTransition('none');
            return;
        }

        // Double-tap detection for touch (mouse uses onDoubleClick),
        // gated to the image itself (2.x `hasClass('lg-image')`).
        if (
            event.pointerType === 'touch' &&
            pointers.size === 1 &&
            isImageTarget(event.target)
        ) {
            const now = Date.now();
            if (now - lastTapRef.current < 300) {
                lastTapRef.current = 0;
                toggleActualSize(eventPoint(event));
                return;
            }
            lastTapRef.current = now;
        }

        if (liveRef.current.zoomed && pointers.size === 1) {
            event.stopPropagation();
            panDragRef.current = {
                pointerId: event.pointerId,
                startX: event.clientX,
                startY: event.clientY,
                samples: [
                    { x: event.clientX, y: event.clientY, t: Date.now() },
                ],
                startPan: liveRef.current.pan,
                moved: false,
            };
            setLiveTransition('none');
        }
    };

    const onDoubleClick = (event: ReactMouseEvent) => {
        if (!enabled || !interactive || !isCurrent) {
            return;
        }
        if (!isImageTarget(event.target)) {
            return;
        }
        toggleActualSize(eventPoint(event));
    };

    if (!enabled) {
        return <>{children}</>;
    }

    const transition =
        transitionMode === 'settle' ? SETTLE_TRANSITION : TRANSITION;
    return (
        <div
            ref={panRef}
            className="lg-zoom-pan"
            style={{
                position: 'absolute',
                inset: 0,
                transform: `translate3d(${zoom.pan.x}px, ${zoom.pan.y}px, 0)`,
                transition,
            }}
            onPointerDown={onPointerDown}
            onDoubleClick={onDoubleClick}
        >
            <div
                ref={scaleElRef}
                className="lg-zoom-scale"
                style={{
                    position: 'absolute',
                    inset: 0,
                    transform: `scale3d(${zoom.scale}, ${zoom.scale}, 1)`,
                    transformOrigin: 'center center',
                    transition,
                }}
            >
                {children}
            </div>
        </div>
    );
}

function useZoomPlugin(ctx: PluginContext): void {
    const enabled = !!(ctx.settings as { zoom?: boolean }).zoom;
    const { layout } = ctx;
    useEffect(() => {
        // Decorative in v3 (transitions are inline on the zoom wrappers;
        // 2.x CSS targeted .lg-img-wrap/.lg-image) — kept as a public
        // CSS hook so consumer stylesheets can target zoom-enabled
        // galleries.
        layout.setOuterClass('lg-use-transition-for-zoom', enabled);
        return () => layout.setOuterClass('lg-use-transition-for-zoom', false);
    }, [enabled, layout]);
}

const Zoom: LgPlugin<ZoomSettings> = {
    name: 'zoom',
    defaults: zoomSettings,
    slots: {
        toolbar: ZoomToolbar,
        slideWrapper: ZoomWrapper,
    },
    usePlugin: useZoomPlugin,
};

declare module '../../types' {
    interface LightGalleryPluginSettings {
        zoom: Partial<ZoomSettings>;
    }
}

export default Zoom;
