// packages/react/src/plugins/video/index.tsx
import {
    useEffect,
    useRef,
    useState,
    type ReactElement,
    type SyntheticEvent,
} from 'react';
import {
    getFacadePoster,
    getSlideType,
    getVideoInfo,
    getVimeoEmbedUrl,
    getWistiaEmbedUrl,
    getYouTubeEmbedUrl,
    getYouTubePosterUrl,
    type PlayerParams,
    type VideoInfo,
} from '@lightgallery/headless';

import { cx } from '../../cx';
import {
    useGalleryActions,
    useGalleryInternal,
    useGallerySettings,
    useGalleryState,
} from '../../context';
import { usePluginSettings } from '../runtime';
import type { GalleryItem } from '../../types';
import type { LgPlugin } from '../types';

/**
 * Video plugin: HTML5 / YouTube / Vimeo / Wistia slides (2.x `lg-video`).
 * The `videojs` option is intentionally dropped — custom players go
 * through `render.slide`.
 */

export interface VideoSettings {
    /** Autoplay the first slide's video once it loads. */
    autoplayFirstVideo: boolean;
    /**
     * Render provider video slides (YouTube/Vimeo/Wistia) as lite
     * facades: a poster with a play button, with the provider iframe
     * created only when the user presses play. The facade poster falls
     * back from the item poster to the YouTube thumbnail endpoint (see
     * `loadYouTubePoster`) to the item thumb; a slide with no resolvable
     * poster keeps the eager-iframe behavior. `autoplayFirstVideo` /
     * `autoplayVideoOnSlide` force an immediate materialize by design.
     * Set false for 2.x eager iframes on all provider slides.
     */
    videoFacade: boolean;
    /**
     * Embed YouTube through the privacy-enhanced youtube-nocookie.com
     * host. Set false to embed through youtube.com; slide URLs that
     * already point at youtube-nocookie.com always keep it.
     */
    youTubeNoCookie: boolean;
    /** Extra YouTube player parameters. */
    youTubePlayerParams: PlayerParams;
    /** Extra Vimeo player parameters. */
    vimeoPlayerParams: PlayerParams;
    /** Extra Wistia player parameters. */
    wistiaPlayerParams: PlayerParams;
    /** Go to the next slide when an HTML5 video ends. */
    gotoNextSlideOnVideoEnd: boolean;
    /** Autoplay videos when their slide becomes current. */
    autoplayVideoOnSlide: boolean;
}

export const videoSettings: VideoSettings = {
    autoplayFirstVideo: true,
    videoFacade: true,
    youTubeNoCookie: true,
    youTubePlayerParams: false,
    vimeoPlayerParams: false,
    wistiaPlayerParams: false,
    gotoNextSlideOnVideoEnd: true,
    autoplayVideoOnSlide: false,
};

interface Html5VideoSource {
    source?: Array<{ src: string; type?: string }>;
    tracks?: Array<Record<string, string>>;
    attributes?: Record<string, string | boolean>;
}

function parseHtml5Video(video: unknown): Html5VideoSource | undefined {
    if (!video) {
        return undefined;
    }
    if (typeof video === 'string') {
        try {
            return JSON.parse(video) as Html5VideoSource;
        } catch {
            return undefined;
        }
    }
    return video as Html5VideoSource;
}

function providerClass(videoInfo: VideoInfo): string {
    if (videoInfo.youtube) {
        return 'lg-has-youtube';
    }
    if (videoInfo.vimeo) {
        return 'lg-has-vimeo';
    }
    if (videoInfo.wistia) {
        return 'lg-has-wistia';
    }
    return 'lg-has-html5';
}

function PlayButton({ label }: { label: string }): ReactElement {
    return (
        <div className="lg-video-play-button">
            <svg
                viewBox="0 0 20 20"
                preserveAspectRatio="xMidYMid"
                focusable="false"
                aria-labelledby={label}
                role="img"
                className="lg-video-play-icon"
            >
                <title>{label}</title>
                <polygon
                    className="lg-video-play-icon-inner"
                    points="1,0 20,10 1,20"
                />
            </svg>
            <svg
                className="lg-video-play-icon-bg"
                viewBox="0 0 50 50"
                focusable="false"
            >
                <circle cx="50%" cy="50%" r="20" />
            </svg>
            <svg
                className="lg-video-play-icon-circle"
                viewBox="0 0 50 50"
                focusable="false"
            >
                <circle cx="50%" cy="50%" r="20" />
            </svg>
        </div>
    );
}

export function VideoSlide({
    item,
    index,
}: {
    item: GalleryItem;
    index: number;
}): ReactElement | null {
    const state = useGalleryState();
    const actions = useGalleryActions();
    const internal = useGalleryInternal();
    const settings = usePluginSettings<VideoSettings>();

    const html5Video = parseHtml5Video(item.video);
    const videoInfo = getVideoInfo(item.src, !!html5Video);

    // Lite-embed facade poster chain (headless): item poster → YouTube
    // thumbnail endpoint (loadYouTubePoster) → item thumb. With
    // videoFacade:false only the 2.x YouTube synthesis remains.
    const poster = settings.videoFacade
        ? getFacadePoster(item, videoInfo, settings.loadYouTubePoster)
        : item.poster ??
          (settings.loadYouTubePoster
              ? getYouTubePosterUrl(videoInfo)
              : undefined);
    const hasPoster = !!poster;
    const [activated, setActivated] = useState(!hasPoster);
    const coreSettings = useGallerySettings();
    // 2.x video-poster dummy (`getVideoPosterMarkup` + dummy content):
    // the first zoom-from-origin slide flies the trigger's already-
    // decoded thumb inside the video cont while the poster loads beneath
    // it; the dummy drops shortly after the load settles. Armed at mount
    // with v2's own condition (first slide + zoomFromOrigin + a sized
    // item — the flight preconditions).
    const [dummySrc, setDummySrc] = useState<string | null>(() =>
        hasPoster &&
        !state.galleryOn &&
        state.currentIndex === index &&
        coreSettings.zoomFromOrigin &&
        item.lgSize &&
        !state.loadedSlides.has(index)
            ? internal.getDummySrc(index)
            : null,
    );
    const loaded = state.loadedSlides.has(index);
    useEffect(() => {
        if (!dummySrc || !loaded) {
            return;
        }
        const timeout = window.setTimeout(() => setDummySrc(null), 300);
        return () => window.clearTimeout(timeout);
    }, [dummySrc, loaded]);
    useEffect(() => {
        if (!dummySrc) {
            return;
        }
        internal.layout.setOuterClass('lg-first-slide-loading', true);
        return () =>
            internal.layout.setOuterClass('lg-first-slide-loading', false);
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [dummySrc]);
    const loadSettleRef = useRef<number | undefined>(undefined);
    useEffect(() => () => window.clearTimeout(loadSettleRef.current), []);
    const pendingPlayRef = useRef(false);
    const mediaRef = useRef<HTMLVideoElement | HTMLIFrameElement | null>(null);
    const isCurrent = state.currentIndex === index;
    const isCurrentRef = useRef(isCurrent);
    isCurrentRef.current = isCurrent;
    const settingsRef = useRef(settings);
    settingsRef.current = settings;

    const control = (action: 'play' | 'pause') => {
        const el = mediaRef.current;
        if (!el || !videoInfo) {
            return;
        }
        if (videoInfo.html5) {
            const video = el as HTMLVideoElement;
            if (action === 'play') {
                void video.play?.()?.catch?.(() => undefined);
            } else {
                video.pause?.();
            }
            return;
        }
        const frame = el as HTMLIFrameElement;
        try {
            if (videoInfo.youtube) {
                frame.contentWindow?.postMessage(
                    `{"event":"command","func":"${action}Video","args":""}`,
                    '*',
                );
            } else if (videoInfo.vimeo) {
                frame.contentWindow?.postMessage(
                    JSON.stringify({ method: action }),
                    '*',
                );
            }
            // Wistia control needs its player API script — deliberately
            // skipped (2.x pushed to window._wq; noted deviation).
        } catch {
            // Cross-origin messaging is best-effort.
        }
    };

    const activateAndPlay = () => {
        pendingPlayRef.current = true;
        setActivated(true);
        // Already activated → the media is (or soon is) ready.
        control('play');
    };

    // hasVideo (informational) + load-state for slides without a poster:
    // a video slide counts as loaded immediately (2.x
    // `isHTML5VideoWithoutPoster` / video-cont path).
    useEffect(() => {
        internal.emit('onHasVideo', {
            index,
            src: item.src,
            html5Video: item.video,
            hasPoster,
        });
        if (!hasPoster && !state.loadedSlides.has(index)) {
            const isFirstSlide = !state.galleryOn;
            actions.dispatch({ type: 'SLIDE_LOADED', index });
            internal.emit('onSlideItemLoad', {
                index,
                delay: 0,
                isFirstSlide,
            });
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    // Autoplay + pause-on-leave via the event bus (2.x event wiring).
    useEffect(() => {
        const offLoad = internal.events.on('slideItemLoad', (detail) => {
            if (detail.index !== index) {
                return;
            }
            const current = isCurrentRef.current;
            const cfg = settingsRef.current;
            if (detail.isFirstSlide && cfg.autoplayFirstVideo && current) {
                window.setTimeout(() => activateAndPlay(), 200);
            } else if (
                !detail.isFirstSlide &&
                cfg.autoplayVideoOnSlide &&
                current
            ) {
                activateAndPlay();
            }
        });
        const offAfter = internal.events.on('afterSlide', (detail) => {
            if (
                settingsRef.current.autoplayVideoOnSlide &&
                detail.index === index &&
                detail.index !== detail.prevIndex
            ) {
                window.setTimeout(() => activateAndPlay(), 100);
            }
        });
        const offBefore = internal.events.on('beforeSlide', (detail) => {
            if (detail.prevIndex === index && detail.index !== index) {
                control('pause');
            }
        });
        return () => {
            offLoad();
            offAfter();
            offBefore();
        };
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    if (!videoInfo) {
        return null;
    }

    const [maxWidth = 1280, maxHeight = 720] = settings.videoMaxSize
        .split('-')
        .map((value) => parseInt(value, 10));

    const onMediaReady = () => {
        if (pendingPlayRef.current) {
            pendingPlayRef.current = false;
            control('play');
        }
    };

    const title = item.title ?? item.alt ?? 'Embedded video player';
    const iframeProps = {
        allow: 'autoplay',
        allowFullScreen: true,
        frameBorder: 0,
        title,
        onLoad: onMediaReady,
    } as const;

    let player: ReactElement | null = null;
    if (activated) {
        if (videoInfo.youtube) {
            player = (
                <iframe
                    {...iframeProps}
                    ref={(el) => {
                        mediaRef.current = el;
                    }}
                    className="lg-video-object lg-youtube"
                    src={getYouTubeEmbedUrl(
                        videoInfo,
                        settings.youTubePlayerParams,
                        item.src ?? '',
                        settings.youTubeNoCookie,
                    )}
                />
            );
        } else if (videoInfo.vimeo) {
            player = (
                <iframe
                    {...iframeProps}
                    ref={(el) => {
                        mediaRef.current = el;
                    }}
                    className="lg-video-object lg-vimeo"
                    src={getVimeoEmbedUrl(
                        videoInfo,
                        settings.vimeoPlayerParams,
                    )}
                />
            );
        } else if (videoInfo.wistia) {
            player = (
                <iframe
                    {...iframeProps}
                    ref={(el) => {
                        mediaRef.current = el;
                    }}
                    className="wistia_embed lg-video-object lg-wistia"
                    name="wistia_embed"
                    src={getWistiaEmbedUrl(
                        videoInfo,
                        settings.wistiaPlayerParams,
                    )}
                />
            );
        } else if (videoInfo.html5 && html5Video) {
            const attributes: Record<string, string | boolean> = {};
            Object.entries(html5Video.attributes ?? {}).forEach(
                ([key, value]) => {
                    attributes[key === 'controlslist' ? 'controlsList' : key] =
                        value;
                },
            );
            player = (
                <video
                    className="lg-video-object lg-html5"
                    ref={(el) => {
                        mediaRef.current = el;
                    }}
                    onLoadedMetadata={onMediaReady}
                    onEnded={() => {
                        if (settingsRef.current.gotoNextSlideOnVideoEnd) {
                            actions.nextSlide();
                        }
                    }}
                    // Keep clicks on the native controls from starting drags.
                    onPointerDown={(event: SyntheticEvent) =>
                        event.stopPropagation()
                    }
                    {...attributes}
                >
                    {html5Video.source?.map((source, sourceIndex) => (
                        <source
                            key={sourceIndex}
                            src={source.src}
                            type={source.type}
                        />
                    ))}
                    {html5Video.tracks?.map((track, trackIndex) => (
                        <track key={trackIndex} {...track} />
                    ))}
                    Your browser does not support HTML5 video.
                </video>
            );
        }
    }

    return (
        <div
            className={cx(
                'lg-video-cont',
                providerClass(videoInfo),
                activated && 'lg-video-loaded',
            )}
            style={{
                width: '100%',
                maxWidth: `${maxWidth}px`,
                maxHeight: '100%',
                aspectRatio: `${maxWidth} / ${maxHeight}`,
            }}
        >
            {player}
            {!activated && hasPoster && (
                <button
                    type="button"
                    className="lg-video-poster-wrap"
                    style={{
                        all: 'unset',
                        cursor: 'pointer',
                        display: 'block',
                        width: '100%',
                        height: '100%',
                    }}
                    aria-label={settings.strings.playVideo}
                    onClick={() => {
                        internal.emit('onPosterClick');
                        activateAndPlay();
                    }}
                >
                    <PlayButton label={settings.strings.playVideo} />
                    <img
                        className="lg-object lg-video-poster"
                        src={poster}
                        alt={item.alt ?? ''}
                        draggable={false}
                        onLoad={() => {
                            if (state.loadedSlides.has(index)) {
                                return;
                            }
                            const isFirstSlide = !state.galleryOn;
                            const complete = () => {
                                actions.dispatch({
                                    type: 'SLIDE_LOADED',
                                    index,
                                });
                                internal.emit('onSlideItemLoad', {
                                    index,
                                    delay: 0,
                                    isFirstSlide,
                                });
                            };
                            // While the zoom-from-origin flight animates
                            // this slide, hold the completion — the state
                            // flip mid-transition restarts the flight in
                            // Safari (the image path holds the same way).
                            if (
                                isFirstSlide &&
                                internal.zoomOriginOpenRef.current
                            ) {
                                loadSettleRef.current = window.setTimeout(
                                    complete,
                                    coreSettings.startAnimationDuration + 120,
                                );
                                return;
                            }
                            complete();
                        }}
                    />
                </button>
            )}
            {dummySrc && (
                <img
                    className="lg-dummy-img"
                    src={dummySrc}
                    alt=""
                    aria-hidden="true"
                    draggable={false}
                    // v2 sizes the dummy to the cont box exactly.
                    style={{
                        position: 'absolute',
                        inset: 0,
                        width: '100%',
                        height: '100%',
                    }}
                />
            )}
        </div>
    );
}

const Video: LgPlugin<VideoSettings> = {
    name: 'video',
    defaults: videoSettings,
    slideRenderer: (item, index) => {
        if (getSlideType(item) !== 'video') {
            return undefined;
        }
        return <VideoSlide item={item} index={index} />;
    },
};

declare module '../../types' {
    interface LightGalleryPluginSettings {
        video: Partial<VideoSettings>;
    }
}

export default Video;

// packages/angular/plugins/video/index.ts
import {
    afterNextRender,
    ChangeDetectionStrategy,
    Component,
    computed,
    DestroyRef,
    effect,
    ElementRef,
    inject,
    input,
    signal,
    untracked,
    viewChild,
} from '@angular/core';
import { DomSanitizer, type SafeResourceUrl } from '@angular/platform-browser';
import {
    getFacadePoster,
    getSlideType,
    getVideoInfo,
    getVimeoEmbedUrl,
    getWistiaEmbedUrl,
    getYouTubeEmbedUrl,
    getYouTubePosterUrl,
    type PlayerParams,
    type VideoInfo,
} from '@lightgallery/headless';
import {
    LG_PLUGIN_CONTEXT,
    type LgFeature,
    type LgGalleryItem,
} from '@lightgallery/angular';

/**
 * Video feature: HTML5 / YouTube / Vimeo / Wistia slides (2.x `lg-video`) —
 * the slide-renderer template other features copy. The `videojs` option
 * is intentionally dropped; custom players go through the `lgSlide`
 * template slot.
 *
 * The embed URLs come from the headless builders (validated video ids), so
 * bypassing Angular's resource-URL sanitizer for them is deliberate and
 * confined to those builders' output.
 */

export interface VideoSettings {
    /** Autoplay the first slide's video once it loads. */
    autoplayFirstVideo: boolean;
    /**
     * Render provider video slides (YouTube/Vimeo/Wistia) as lite
     * facades: a poster with a play button, with the provider iframe
     * created only when the user presses play. The facade poster falls
     * back from the item poster to the YouTube thumbnail endpoint (see
     * `loadYouTubePoster`) to the item thumb; a slide with no resolvable
     * poster keeps the eager-iframe behavior. `autoplayFirstVideo` /
     * `autoplayVideoOnSlide` force an immediate materialize by design.
     * Set false for 2.x eager iframes on all provider slides.
     */
    videoFacade: boolean;
    /**
     * Embed YouTube through the privacy-enhanced youtube-nocookie.com
     * host. Set false to embed through youtube.com; slide URLs that
     * already point at youtube-nocookie.com always keep it.
     */
    youTubeNoCookie: boolean;
    /** Extra YouTube player parameters. */
    youTubePlayerParams: PlayerParams;
    /** Extra Vimeo player parameters. */
    vimeoPlayerParams: PlayerParams;
    /** Extra Wistia player parameters. */
    wistiaPlayerParams: PlayerParams;
    /** Go to the next slide when an HTML5 video ends. */
    gotoNextSlideOnVideoEnd: boolean;
    /** Autoplay videos when their slide becomes current. */
    autoplayVideoOnSlide: boolean;
}

export const videoSettings: VideoSettings = {
    autoplayFirstVideo: true,
    videoFacade: true,
    youTubeNoCookie: true,
    youTubePlayerParams: false,
    vimeoPlayerParams: false,
    wistiaPlayerParams: false,
    gotoNextSlideOnVideoEnd: true,
    autoplayVideoOnSlide: false,
};

interface Html5VideoSource {
    source?: Array<{ src: string; type?: string }>;
    tracks?: Array<Record<string, string>>;
    attributes?: Record<string, string | boolean>;
}

function parseHtml5Video(video: unknown): Html5VideoSource | undefined {
    if (!video) {
        return undefined;
    }
    if (typeof video === 'string') {
        try {
            return JSON.parse(video) as Html5VideoSource;
        } catch {
            return undefined;
        }
    }
    return video as Html5VideoSource;
}

function providerClass(videoInfo: VideoInfo): string {
    if (videoInfo.youtube) {
        return 'lg-has-youtube';
    }
    if (videoInfo.vimeo) {
        return 'lg-has-vimeo';
    }
    if (videoInfo.wistia) {
        return 'lg-has-wistia';
    }
    return 'lg-has-html5';
}

type VideoResolved = VideoSettings & {
    videoMaxSize: string;
    loadYouTubePoster: boolean;
    strings: { playVideo: string };
};

@Component({
    selector: 'lg-video-slide',
    changeDetection: ChangeDetectionStrategy.OnPush,
    template: `
        @if (info(); as info) {
        <div
            class="lg-video-cont"
            [class]="contClasses()"
            [style.width]="'100%'"
            [style.max-width.px]="maxSize().width"
            [style.max-height]="'100%'"
            [style.aspect-ratio]="maxSize().width + ' / ' + maxSize().height"
        >
            @if (showPlayer()) { @if (embedUrl(); as url) {
            <iframe
                #media
                [class]="iframeClasses()"
                [attr.name]="info.wistia ? 'wistia_embed' : null"
                [src]="url"
                allow="autoplay"
                allowfullscreen
                frameborder="0"
                [attr.title]="mediaTitle()"
                (load)="onMediaReady()"
            ></iframe>
            } @else if (html5()) {
            <video
                #media
                class="lg-video-object lg-html5"
                (loadedmetadata)="onMediaReady()"
                (ended)="onVideoEnded()"
                (pointerdown)="$event.stopPropagation()"
            >
                @for ( source of html5()?.source ?? []; track $index ) {
                <source
                    [attr.src]="source.src"
                    [attr.type]="source.type ?? null"
                />
                } @for ( track of html5()?.tracks ?? []; track $index ) {
                <track
                    [attr.kind]="track['kind'] ?? null"
                    [attr.src]="track['src'] ?? null"
                    [attr.srclang]="track['srclang'] ?? null"
                    [attr.label]="track['label'] ?? null"
                    [attr.default]="track['default'] ?? null"
                />
                } Your browser does not support HTML5 video.
            </video>
            } } @if (!activated() && hasPoster() && !holdPoster()) {
            <button
                type="button"
                class="lg-video-poster-wrap"
                style="
                            all: unset;
                            cursor: pointer;
                            display: block;
                            width: 100%;
                            height: 100%;
                        "
                [attr.aria-label]="settings().strings.playVideo"
                (click)="onPosterClick()"
            >
                <div class="lg-video-play-button">
                    <svg
                        viewBox="0 0 20 20"
                        preserveAspectRatio="xMidYMid"
                        focusable="false"
                        role="img"
                        class="lg-video-play-icon"
                    >
                        <title>
                            {{ settings().strings.playVideo }}
                        </title>
                        <polygon
                            class="lg-video-play-icon-inner"
                            points="1,0 20,10 1,20"
                        />
                    </svg>
                    <svg
                        class="lg-video-play-icon-bg"
                        viewBox="0 0 50 50"
                        focusable="false"
                    >
                        <circle cx="50%" cy="50%" r="20" />
                    </svg>
                    <svg
                        class="lg-video-play-icon-circle"
                        viewBox="0 0 50 50"
                        focusable="false"
                    >
                        <circle cx="50%" cy="50%" r="20" />
                    </svg>
                </div>
                <img
                    class="lg-object lg-video-poster"
                    [src]="poster()"
                    [alt]="item().alt ?? ''"
                    draggable="false"
                    (load)="onPosterLoad()"
                />
            </button>
            } @if (dummySrc(); as dummy) {
            <!-- v2 sizes the dummy to the cont box exactly. -->
            <img
                class="lg-dummy-img"
                [attr.src]="dummy"
                alt=""
                aria-hidden="true"
                draggable="false"
                style="
                            position: absolute;
                            inset: 0;
                            width: 100%;
                            height: 100%;
                        "
            />
            }
        </div>
        }
    `,
})
export class LgVideoSlideComponent {
    readonly item = input.required<LgGalleryItem>();
    readonly index = input.required<number>();

    private readonly ctx = inject(LG_PLUGIN_CONTEXT);
    private readonly sanitizer = inject(DomSanitizer);

    protected readonly settings = computed(
        () => this.ctx.settings() as unknown as VideoResolved,
    );
    protected readonly html5 = computed(() =>
        parseHtml5Video(this.item().video),
    );
    protected readonly info = computed(() =>
        getVideoInfo(this.item().src, !!this.html5()),
    );
    // Lite-embed facade poster chain (headless): item poster → YouTube
    // thumbnail endpoint (loadYouTubePoster) → item thumb. With
    // videoFacade:false only the 2.x YouTube synthesis remains.
    protected readonly poster = computed(() => {
        const item = this.item();
        const settings = this.settings();
        if (settings.videoFacade) {
            return getFacadePoster(
                item,
                this.info(),
                settings.loadYouTubePoster,
            );
        }
        return (
            item.poster ??
            (settings.loadYouTubePoster
                ? getYouTubePosterUrl(this.info())
                : undefined)
        );
    });
    protected readonly hasPoster = computed(() => !!this.poster());
    protected readonly activated = signal(false);

    // 2.x video-poster dummy (`getVideoPosterMarkup` + dummy content):
    // the first zoom-from-origin slide flies the trigger's already-
    // decoded thumb inside the video cont while the poster loads beneath
    // it; the dummy drops shortly after the load settles.
    protected readonly dummySrc = signal<string | null>(null);
    private dummyDone = false;
    private dummyDropTimer: ReturnType<typeof setTimeout> | null = null;
    private readonly slideLoaded = computed(() =>
        this.ctx.state().loadedSlides.has(this.index()),
    );
    /** The poster mounts only once the flight lands (v2 defers the real
     *  markup the same way; the image path defers via deferSrc). */
    protected readonly holdPoster = computed(
        () => !!this.dummySrc() && this.ctx.zoomOriginOpen(),
    );
    protected readonly showPlayer = computed(
        () => this.activated() || !this.hasPoster(),
    );
    protected readonly contClasses = computed(() => {
        const info = this.info();
        return [
            info ? providerClass(info) : '',
            this.showPlayer() ? 'lg-video-loaded' : '',
        ]
            .filter(Boolean)
            .join(' ');
    });
    protected readonly iframeClasses = computed(() => {
        const info = this.info();
        if (info?.youtube) {
            return 'lg-video-object lg-youtube';
        }
        if (info?.vimeo) {
            return 'lg-video-object lg-vimeo';
        }
        return 'wistia_embed lg-video-object lg-wistia';
    });
    protected readonly maxSize = computed(() => {
        const [width = 1280, height = 720] = this.settings()
            .videoMaxSize.split('-')
            .map((value) => parseInt(value, 10));
        return { width, height };
    });
    protected readonly mediaTitle = computed(
        () => this.item().title ?? this.item().alt ?? 'Embedded video player',
    );
    protected readonly embedUrl = computed<SafeResourceUrl | null>(() => {
        const info = this.info();
        const settings = this.settings();
        if (!info) {
            return null;
        }
        let url: string | undefined;
        if (info.youtube) {
            url = getYouTubeEmbedUrl(
                info,
                settings.youTubePlayerParams,
                this.item().src ?? '',
                settings.youTubeNoCookie,
            );
        } else if (info.vimeo) {
            url = getVimeoEmbedUrl(info, settings.vimeoPlayerParams);
        } else if (info.wistia) {
            url = getWistiaEmbedUrl(info, settings.wistiaPlayerParams);
        }
        return url ? this.sanitizer.bypassSecurityTrustResourceUrl(url) : null;
    });

    private readonly mediaEl = viewChild<ElementRef<HTMLElement>>('media');
    private pendingPlay = false;
    private playTimer: ReturnType<typeof setTimeout> | null = null;

    constructor() {
        // Dummy lifecycle: armed while the origin flight runs for this
        // (first, unloaded, poster-carrying, sized) slide; dropped 300ms
        // after the poster load settles.
        effect(() => {
            const flightRunning = this.ctx.zoomOriginOpen();
            if (
                this.dummyDone ||
                this.dummySrc() ||
                !flightRunning ||
                !this.hasPoster() ||
                !this.item().lgSize ||
                this.ctx.state().galleryOn ||
                this.ctx.state().currentIndex !== this.index() ||
                this.ctx.state().loadedSlides.has(this.index())
            ) {
                return;
            }
            untracked(() => {
                const src = this.ctx.getDummySrc(this.index());
                if (src) {
                    this.dummySrc.set(src);
                    this.ctx.layout.setOuterClass(
                        'lg-first-slide-loading',
                        true,
                    );
                } else {
                    this.dummyDone = true;
                }
            });
        });
        effect(() => {
            if (!this.dummySrc() || !this.slideLoaded()) {
                return;
            }
            untracked(() => {
                this.dummyDropTimer = setTimeout(() => {
                    this.dummyDone = true;
                    this.dummySrc.set(null);
                    this.ctx.layout.setOuterClass(
                        'lg-first-slide-loading',
                        false,
                    );
                }, 300);
            });
        });
        inject(DestroyRef).onDestroy(() => {
            if (this.dummyDropTimer !== null) {
                clearTimeout(this.dummyDropTimer);
            }
            if (this.dummySrc()) {
                this.ctx.layout.setOuterClass('lg-first-slide-loading', false);
            }
        });
        // hasVideo (informational) + load-state for slides without a poster:
        // a video slide counts as loaded immediately (2.x parity).
        afterNextRender(() => {
            const index = this.index();
            const item = this.item();
            this.ctx.emit('hasVideo', {
                index,
                src: item.src,
                html5Video: item.video,
                hasPoster: untracked(this.hasPoster),
            });
            if (!untracked(this.hasPoster)) {
                this.markLoaded();
            }
        });
        // Apply the item's arbitrary html5 `attributes` record (controls,
        // muted, playsinline, ...) — Angular templates cannot spread
        // attributes, so this is imperative on purpose.
        effect(() => {
            const el = this.mediaEl()?.nativeElement;
            const html5 = this.html5();
            if (!el || !html5 || el.tagName !== 'VIDEO') {
                return;
            }
            Object.entries(html5.attributes ?? {}).forEach(([key, value]) => {
                if (value === false) {
                    el.removeAttribute(key);
                } else {
                    el.setAttribute(key, value === true ? '' : String(value));
                }
            });
        });
        // Autoplay + pause-on-leave via the event bus (2.x event wiring).
        const offs = [
            this.ctx.events.on('slideItemLoad', (detail) => {
                if (detail.index !== this.index()) {
                    return;
                }
                const current = this.isCurrent();
                const cfg = untracked(this.settings);
                if (detail.isFirstSlide && cfg.autoplayFirstVideo && current) {
                    this.playTimer = setTimeout(
                        () => this.activateAndPlay(),
                        200,
                    );
                } else if (
                    !detail.isFirstSlide &&
                    cfg.autoplayVideoOnSlide &&
                    current
                ) {
                    this.activateAndPlay();
                }
            }),
            this.ctx.events.on('afterSlide', (detail) => {
                if (
                    untracked(this.settings).autoplayVideoOnSlide &&
                    detail.index === this.index() &&
                    detail.index !== detail.prevIndex
                ) {
                    this.playTimer = setTimeout(
                        () => this.activateAndPlay(),
                        100,
                    );
                }
            }),
            this.ctx.events.on('beforeSlide', (detail) => {
                if (
                    detail.prevIndex === this.index() &&
                    detail.index !== this.index()
                ) {
                    this.control('pause');
                }
            }),
        ];
        inject(DestroyRef).onDestroy(() => {
            offs.forEach((off) => off());
            if (this.playTimer !== null) {
                clearTimeout(this.playTimer);
            }
        });
    }

    private isCurrent(): boolean {
        return this.ctx.state().currentIndex === this.index();
    }

    private markLoaded(): void {
        const index = this.index();
        const state = this.ctx.state();
        if (state.loadedSlides.has(index)) {
            return;
        }
        const isFirstSlide = !state.galleryOn;
        this.ctx.actions.dispatch({ type: 'SLIDE_LOADED', index });
        this.ctx.emit('slideItemLoad', { index, delay: 0, isFirstSlide });
    }

    private control(action: 'play' | 'pause'): void {
        const el = this.mediaEl()?.nativeElement;
        const info = untracked(this.info);
        if (!el || !info) {
            return;
        }
        if (info.html5) {
            const video = el as HTMLVideoElement;
            if (action === 'play') {
                void video.play?.()?.catch?.(() => undefined);
            } else {
                video.pause?.();
            }
            return;
        }
        const frame = el as HTMLIFrameElement;
        try {
            if (info.youtube) {
                frame.contentWindow?.postMessage(
                    `{"event":"command","func":"${action}Video","args":""}`,
                    '*',
                );
            } else if (info.vimeo) {
                frame.contentWindow?.postMessage(
                    JSON.stringify({ method: action }),
                    '*',
                );
            }
            // Wistia control needs its player API script — deliberately
            // skipped (2.x pushed to window._wq; noted deviation).
        } catch {
            // Cross-origin messaging is best-effort.
        }
    }

    private activateAndPlay(): void {
        this.pendingPlay = true;
        this.activated.set(true);
        // Already activated → the media is (or soon is) ready.
        this.control('play');
    }

    protected onMediaReady(): void {
        if (this.pendingPlay) {
            this.pendingPlay = false;
            this.control('play');
        }
    }

    protected onVideoEnded(): void {
        if (untracked(this.settings).gotoNextSlideOnVideoEnd) {
            this.ctx.actions.nextSlide();
        }
    }

    protected onPosterClick(): void {
        this.ctx.emit('posterClick', undefined);
        this.activateAndPlay();
    }

    protected onPosterLoad(): void {
        this.markLoaded();
    }
}

export function withVideo(
    options: Partial<VideoSettings> = {},
): LgFeature<VideoSettings> {
    return {
        name: 'video',
        defaults: videoSettings,
        options,
        slideRenderer: {
            component: LgVideoSlideComponent,
            canRender: (item) => getSlideType(item) === 'video',
        },
    };
}
