// packages/angular/src/lib/image-slide.component.ts
import {
    ChangeDetectionStrategy,
    Component,
    input,
    output,
} from '@angular/core';

import type { LgGalleryItem } from './types';

/**
 * Default image renderer: `<picture class="lg-img-wrap">` with optional
 * `<source>` entries and the `lg-object lg-image` img — the same DOM the
 * vanilla core produces, so `lightgallery/css` styles it unchanged.
 */
@Component({
    selector: 'lg-image-slide',
    changeDetection: ChangeDetectionStrategy.OnPush,
    template: `
        <picture class="lg-img-wrap">
            @if (!deferSrc()) { @for (source of item().sources ?? []; track
            $index) {
            <source
                [attr.media]="source.media ?? null"
                [attr.srcset]="source.srcset"
                [attr.sizes]="source.sizes ?? null"
                [attr.type]="source.type ?? null"
            />
            }
            <img
                class="lg-object lg-image"
                [attr.data-index]="index()"
                [attr.src]="item().src ?? null"
                [attr.srcset]="item().srcset ?? null"
                [attr.sizes]="item().sizes ?? null"
                [alt]="item().alt ?? ''"
                draggable="false"
                (load)="mediaLoad.emit($event)"
                (error)="mediaError.emit()"
                (dragstart)="$event.preventDefault()"
            />
            } @if (dummySrc(); as dummy) {
            <!-- v2 sizes the dummy to the fitted image box with
                     inline width/height; containing it inside the full
                     wrap lands the same visible box without measuring. -->
            <img
                class="lg-dummy-img"
                [attr.src]="dummy"
                alt=""
                aria-hidden="true"
                draggable="false"
                style="width: 100%; height: 100%; object-fit: contain; transform: translate(-50%, -50%)"
            />
            }
        </picture>
    `,
})
export class LgImageSlideComponent {
    readonly item = input.required<LgGalleryItem>();
    readonly index = input.required<number>();
    /** First-slide dummy (2.x): the thumb that flies while `src` loads. */
    readonly dummySrc = input<string | null>(null);
    /** Hold back the real img while the origin flight runs (2.x). */
    readonly deferSrc = input(false);
    /** Native image dragging would swallow the swipe gesture. */
    readonly mediaLoad = output<Event>();
    readonly mediaError = output<void>();
}

// packages/react/src/ImageSlide.tsx
import type { ReactElement } from 'react';

import type { GalleryItem } from './types';

export interface ImageSlideProps {
    item: GalleryItem;
    index: number;
    /** First-slide dummy (2.x): the thumb that flies while `src` loads. */
    dummySrc?: string | null;
    /** Hold back the real `<img>` while the origin flight runs (2.x). */
    deferSrc?: boolean;
    onLoad: () => void;
    onError: () => void;
}

/**
 * Default image renderer: `<picture class="lg-img-wrap">` with optional
 * `<source>` entries and the `lg-object lg-image` img — the same DOM the
 * vanilla core produces, so `lightgallery/css` styles it unchanged.
 */
export function ImageSlide({
    item,
    index,
    dummySrc,
    deferSrc,
    onLoad,
    onError,
}: ImageSlideProps): ReactElement {
    return (
        <picture className="lg-img-wrap">
            {!deferSrc &&
                item.sources?.map((source, sourceIndex) => (
                    <source
                        key={sourceIndex}
                        media={source.media}
                        srcSet={source.srcset}
                        sizes={source.sizes}
                        type={source.type}
                    />
                ))}
            {!deferSrc && (
                <img
                    className="lg-object lg-image"
                    data-index={index}
                    src={item.src}
                    srcSet={item.srcset}
                    sizes={item.sizes}
                    alt={item.alt ?? ''}
                    onLoad={onLoad}
                    onError={onError}
                    // Native image dragging would swallow the swipe gesture.
                    draggable={false}
                    onDragStart={(event) => event.preventDefault()}
                />
            )}
            {dummySrc && (
                <img
                    className="lg-dummy-img"
                    src={dummySrc}
                    alt=""
                    aria-hidden="true"
                    draggable={false}
                    // v2 sizes the dummy to the fitted image box with
                    // inline width/height; containing it inside the full
                    // wrap lands the same visible box without measuring.
                    style={{
                        width: '100%',
                        height: '100%',
                        objectFit: 'contain',
                        transform: 'translate(-50%, -50%)',
                    }}
                />
            )}
        </picture>
    );
}
