// packages/react/src/Caption.tsx
import { useEffect, type ReactElement, type ReactNode } from 'react';

import { cx } from './cx';
import {
    useGalleryInternal,
    useGallerySettings,
    useGallerySlots,
    useGalleryState,
} from './context';
import type { GalleryItem } from './types';

/**
 * Caption content resolution (ADR 0001 §4/§7): the `render.caption` slot
 * wins, then the item's `caption` ReactNode; raw HTML only via the explicit
 * `captionHtml` opt-in, rendered with `dangerouslySetInnerHTML`.
 */
export function CaptionContent({
    item,
    index,
}: {
    item: GalleryItem;
    index: number;
}): ReactElement | null {
    const slots = useGallerySlots();
    let content: ReactNode = null;
    if (slots.caption) {
        content = slots.caption(item, index);
    } else if (item.caption != null) {
        content = item.caption;
    } else if (item.captionHtml) {
        return <div dangerouslySetInnerHTML={{ __html: item.captionHtml }} />;
    }
    return content == null ? null : <>{content}</>;
}

function hasCaption(item: GalleryItem | undefined): boolean {
    return !!item && (item.caption != null || !!item.captionHtml);
}

/** The shared caption bar (`.lg-sub-html`) for 'bar' and 'outer' positions. */
export function Caption(): ReactElement {
    const state = useGalleryState();
    const internal = useGalleryInternal();
    const settings = useGallerySettings();
    const slots = useGallerySlots();
    const item = internal.items[state.currentIndex];

    // 2.x afterAppendSubHtml: fired whenever the caption is (re)written.
    const currentIndex = state.currentIndex;
    useEffect(() => {
        internal.emit('onAfterAppendSubHtml', { index: currentIndex });
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [currentIndex]);
    const empty = !slots.caption && !hasCaption(item);
    // The announcer (when active) voices caption changes; a second live
    // region here would double-announce every slide.
    const a11yProps = settings.ariaAnnouncements
        ? undefined
        : ({ role: 'status', 'aria-live': 'polite' } as const);
    return (
        <div
            className={cx('lg-sub-html', empty && 'lg-empty-html')}
            {...a11yProps}
        >
            {item && !empty && (
                <CaptionContent item={item} index={state.currentIndex} />
            )}
        </div>
    );
}

// packages/angular/src/lib/caption.component.ts
import { NgTemplateOutlet } from '@angular/common';
import {
    ChangeDetectionStrategy,
    Component,
    computed,
    effect,
    inject,
    input,
    untracked,
} from '@angular/core';

import { LgGalleryRuntime } from './runtime';
import type { LgCaptionContext } from './slots';
import type { LgGalleryItem } from './types';

/**
 * Caption content resolution (ADR 0001 §4): the `*lgCaption` slot template
 * wins, then the item's `caption` string; raw HTML only via the explicit
 * `captionHtml` opt-in — rendered with `[innerHTML]`, subject to Angular's
 * sanitizer (documented deviation vs React's `dangerouslySetInnerHTML`).
 */
@Component({
    selector: 'lg-caption-content',
    changeDetection: ChangeDetectionStrategy.OnPush,
    imports: [NgTemplateOutlet],
    template: `
        @if (slot(); as slot) {
        <ng-container
            *ngTemplateOutlet="slot.templateRef; context: context()"
        />
        } @else if (item()?.caption != null) {
        {{ item()?.caption }}
        } @else if (item()?.captionHtml) {
        <div [innerHTML]="item()?.captionHtml"></div>
        }
    `,
})
export class LgCaptionContentComponent {
    readonly item = input<LgGalleryItem | undefined>(undefined);
    readonly index = input.required<number>();

    private readonly runtime = inject(LgGalleryRuntime);
    protected readonly slot = computed(() => this.runtime.slots.caption());
    protected readonly context = computed<LgCaptionContext>(() => ({
        $implicit: this.item(),
        index: this.index(),
    }));
}

function hasCaption(item: LgGalleryItem | undefined): boolean {
    return !!item && (item.caption != null || !!item.captionHtml);
}

/** The caption bar (`.lg-sub-html`) for 'bar' and 'outer' positions. */
@Component({
    selector: 'lg-caption',
    changeDetection: ChangeDetectionStrategy.OnPush,
    imports: [LgCaptionContentComponent],
    host: {
        '[class.lg-sub-html]': 'true',
        '[class.lg-empty-html]': 'empty()',
        // The announcer (when active) voices caption changes; a second
        // live region here would double-announce every slide.
        '[attr.role]': "live() ? 'status' : null",
        '[attr.aria-live]': "live() ? 'polite' : null",
    },
    template: `
        @if (item() && !empty()) {
        <lg-caption-content [item]="item()" [index]="index()" />
        }
    `,
})
export class LgCaptionComponent {
    readonly item = input<LgGalleryItem | undefined>(undefined);
    readonly index = input.required<number>();

    private readonly runtime = inject(LgGalleryRuntime);
    protected readonly empty = computed(
        () => !this.runtime.slots.caption() && !hasCaption(this.item()),
    );
    protected readonly live = computed(
        () => this.runtime.settings().ariaAnnouncements === false,
    );

    constructor() {
        // React counterpart: Caption's afterAppendSubHtml effect — fired
        // whenever the caption bar is (re)written for a new index.
        effect(() => {
            const index = this.index();
            untracked(() => this.runtime.emit('afterAppendSubHtml', { index }));
        });
    }
}
