// packages/react/src/IframeSlide.tsx
import type { ReactElement } from 'react';

import { useGallerySettings } from './context';
import type { GalleryItem } from './types';

export interface IframeSlideProps {
    item: GalleryItem;
    index: number;
    onLoad: () => void;
}

/** Iframe slide renderer (deferred from plan 003), 2.x `getIframeMarkup`. */
export function IframeSlide({
    item,
    onLoad,
}: IframeSlideProps): ReactElement {
    const settings = useGallerySettings();
    return (
        <div
            className="lg-media-cont lg-has-iframe"
            style={{
                width: settings.iframeWidth,
                maxWidth: settings.iframeMaxWidth,
                height: settings.iframeHeight,
                maxHeight: settings.iframeMaxHeight,
            }}
        >
            <iframe
                className="lg-object"
                title={item.iframeTitle ?? item.title ?? 'Embedded content'}
                src={item.src}
                allowFullScreen={true}
                onLoad={onLoad}
            />
        </div>
    );
}

// packages/angular/src/lib/iframe-slide.component.ts
import {
    ChangeDetectionStrategy,
    Component,
    inject,
    input,
    output,
} from '@angular/core';

import { LgGalleryRuntime } from './runtime';
import type { LgGalleryItem } from './types';

/** Iframe slide renderer (deferred from plan 003), 2.x `getIframeMarkup`. */
@Component({
    selector: 'lg-iframe-slide',
    changeDetection: ChangeDetectionStrategy.OnPush,
    template: `
        <div
            class="lg-media-cont lg-has-iframe"
            [style.width]="runtime.settings().iframeWidth"
            [style.max-width]="runtime.settings().iframeMaxWidth"
            [style.height]="runtime.settings().iframeHeight"
            [style.max-height]="runtime.settings().iframeMaxHeight"
        >
            <iframe
                class="lg-object"
                [attr.title]="
                    item().iframeTitle ?? item().title ?? 'Embedded content'
                "
                [attr.src]="item().src ?? null"
                allowfullscreen
                (load)="mediaLoad.emit()"
            ></iframe>
        </div>
    `,
})
export class LgIframeSlideComponent {
    readonly item = input.required<LgGalleryItem>();
    readonly index = input.required<number>();
    readonly mediaLoad = output<void>();

    protected readonly runtime = inject(LgGalleryRuntime);
}
