// packages/react/src/Slide.tsx
import {
    useEffect,
    useMemo,
    useRef,
    useState,
    type CSSProperties,
    type ReactElement,
    type ReactNode,
} from 'react';
import {
    awaitDecode,
    getPreloadIndexes,
    getSlideType,
    type ImageSize,
} from '@lightgallery/headless';

import { CaptionContent } from './Caption';
import { cx } from './cx';
import {
    useGalleryActions,
    useGalleryInternal,
    useGallerySettings,
    useGalleryState,
} from './context';
import type { OriginAnimation } from './GalleryOutlet';
import { useEventCallback, useIsoLayoutEffect } from './hooks';
import { IframeSlide } from './IframeSlide';
import { ImageSlide } from './ImageSlide';
import {
    resolvePluginSlideContent,
    usePluginContext,
    wrapSlideContent,
} from './plugins/runtime';
import type { GalleryItem } from './types';

export interface SlideProps {
    index: number;
    item: GalleryItem | undefined;
    isShown: boolean;
    position: 'prev' | 'next' | undefined;
    inProgress: boolean;
    originAnim: OriginAnimation | null;
}

/**
 * One `.lg-item`. Content mounts lazily (2.x parity): the current slide loads
 * immediately; neighbors within `preload` load once the current slide's media
 * completes; once loaded, a slide keeps its content for as long as it stays
 * in the DOM window. The vanilla CSS shows the loading spinner until
 * `lg-complete` lands.
 */
export function Slide({
    index,
    item,
    isShown,
    position,
    inProgress,
    originAnim,
}: SlideProps): ReactElement {
    const state = useGalleryState();
    const settings = useGallerySettings();
    const actions = useGalleryActions();
    const internal = useGalleryInternal();

    const [error, setError] = useState(false);

    const isCurrent = state.currentIndex === index;
    const completed = state.loadedSlides.has(index) || error;
    const currentLoaded = state.loadedSlides.has(state.currentIndex);
    const inPreloadRange = useMemo(
        () =>
            getPreloadIndexes(
                state.currentIndex,
                settings.preload,
                state.slidesCount,
            ).indexOf(index) !== -1,
        [state.currentIndex, settings.preload, state.slidesCount, index],
    );
    const stickyLoadRef = useRef(false);
    // Sticky content survives `state.open` flipping false at close-START:
    // the close flight animates this slide back to the thumbnail, and an
    // `open`-gated unmount would fly an EMPTY item (invisible close).
    // Teardown belongs to the item's own unmount once the close settles
    // (Slides `cleared`) — the moment 2.x empties `$inner`.
    const shouldLoad =
        stickyLoadRef.current ||
        (state.open && (isCurrent || (currentLoaded && inPreloadRange)));
    if (shouldLoad) {
        stickyLoadRef.current = true;
    }

    // 2.x afterAppendSlide: fired once when the slide's content mounts.
    const appendedRef = useRef(false);
    useEffect(() => {
        if (shouldLoad && !appendedRef.current) {
            appendedRef.current = true;
            internal.emit('onAfterAppendSlide', { index });
            if (settings.captionPosition === 'slide') {
                internal.emit('onAfterAppendSubHtml', { index });
            }
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [shouldLoad]);

    const handleLoad = useEventCallback(
        (event?: { currentTarget?: EventTarget | null }) => {
            if (state.loadedSlides.has(index)) {
                return;
            }
            const isFirstSlide = !state.galleryOn;
            const complete = () => {
                actions.dispatch({ type: 'SLIDE_LOADED', index });
                internal.emit('onSlideItemLoad', {
                    index,
                    delay: loadDelay(isFirstSlide),
                    isFirstSlide,
                });
            };
            const proceed = () => {
                if (unmountedRef.current) {
                    return;
                }
                // While the zoom-from-origin flight is animating THIS
                // slide, hold the completion: the class/state flip
                // rewrites the flying element's attributes
                // mid-transition, which Safari answers by restarting the
                // transition (visible flicker whenever a cached image
                // loads instantly — e.g. reopening on the same slide).
                // v2 is immune because it flies an isolated dummy image.
                if (isFirstSlide && internal.zoomOriginOpenRef.current) {
                    loadSettleRef.current = window.setTimeout(
                        complete,
                        settings.startAnimationDuration + 120,
                    );
                    return;
                }
                complete();
            };
            // Decode gate: `lg-complete` flips only once the browser can
            // paint the FULL image — a loaded-but-undecoded flip paints
            // partially on slow devices. Synchronous when `decode()` is
            // unavailable (the load event already fired); the timeout
            // fallback keeps a stalling decode from stranding the
            // spinner.
            const target = event?.currentTarget;
            if (
                target instanceof HTMLImageElement &&
                typeof target.decode === 'function'
            ) {
                void awaitDecode(target).then(proceed);
                return;
            }
            proceed();
        },
    );
    const unmountedRef = useRef(false);
    useEffect(() => {
        // Reset on mount, not just set on unmount: StrictMode's
        // mount→cleanup→remount cycle would otherwise leave the flag
        // stuck true and silently swallow every completion.
        unmountedRef.current = false;
        return () => {
            unmountedRef.current = true;
        };
    }, []);
    const loadSettleRef = useRef<number | undefined>(undefined);
    useEffect(() => () => window.clearTimeout(loadSettleRef.current), []);
    const loadDelay = (isFirstSlide: boolean): number =>
        isFirstSlide
            ? (settings.zoomFromOrigin
                  ? settings.startAnimationDuration
                  : settings.backdropDuration) + 10
            : 0;
    const handleError = useEventCallback(() => {
        if (state.loadedSlides.has(index)) {
            return;
        }
        const isFirstSlide = !state.galleryOn;
        // A failed load settles the slide too (2.x fires slideItemLoad on
        // error): the error message is on screen, neighbours may preload
        // and the slideshow moves on instead of waiting forever.
        const complete = () => {
            if (unmountedRef.current) {
                return;
            }
            setError(true);
            actions.dispatch({ type: 'SLIDE_ERROR', index });
            internal.emit('onSlideItemLoad', {
                index,
                delay: loadDelay(isFirstSlide),
                isFirstSlide,
            });
        };
        // Same hold as a load: swapping the flying element's content
        // mid-flight restarts the transition in Safari.
        if (isFirstSlide && internal.zoomOriginOpenRef.current) {
            loadSettleRef.current = window.setTimeout(
                complete,
                settings.startAnimationDuration + 120,
            );
            return;
        }
        complete();
    });

    let style: CSSProperties | undefined;
    let originClasses: string | false = false;
    if (originAnim) {
        if (originAnim.stage === 'init') {
            style = {
                transform: originAnim.transform,
                // The origin transform must LAND, never animate: measuring
                // (computeOrigin) forces a recalc that baselines the item
                // at identity, and the `:not(.lg-start-end-progress)`
                // inherit rule would transition identity → origin — a
                // visible fullscreen→thumbnail shrink before the flight.
                // (v2 batches transform + flight classes into one style
                // change event, so it never trips this.)
                transitionProperty: 'none',
            };
        } else {
            style = {
                transform:
                    originAnim.stage === 'run' && !originAnim.closing
                        ? 'translate3d(0, 0, 0)'
                        : originAnim.transform,
                transitionDuration: `${settings.startAnimationDuration}ms`,
            };
            originClasses = originAnim.closing
                ? 'lg-start-end-progress'
                : 'lg-start-progress lg-start-end-progress';
        }
    }

    const slideType = item ? getSlideType(item) : 'image';
    const pluginCtx = usePluginContext();

    // 2.x first-slide dummy (`getDummyImageContent`): while the
    // zoom-from-origin flight runs, the trigger's already-decoded
    // thumbnail flies enlarged in place of the still-loading image; the
    // real image loads beneath it and the dummy drops shortly after the
    // load settles (`loadContentOnFirstSlideLoad`). Layout effect: the
    // dummy must be in the flight's FIRST painted frame.
    const [dummySrc, setDummySrc] = useState<string | null>(null);
    const [dummySize, setDummySize] = useState<ImageSize | null>(null);
    const [dummyOffset, setDummyOffset] = useState<{
        x: number;
        y: number;
    } | null>(null);
    const dummyDoneRef = useRef(false);
    useIsoLayoutEffect(() => {
        if (
            dummyDoneRef.current ||
            dummySrc ||
            !originAnim ||
            originAnim.closing ||
            completed ||
            slideType !== 'image'
        ) {
            return;
        }
        const src = originAnim.dummySrc ?? internal.getDummySrc(index);
        if (src) {
            setDummySrc(src);
            // A plugin's flight may cover only a region of the image with
            // the dummy (origin crop's pre-cropped thumbnail files).
            const { imageSize, region } = originAnim;
            if (imageSize && region) {
                setDummySize({
                    width: imageSize.width * region.width,
                    height: imageSize.height * region.height,
                });
                setDummyOffset({
                    x: imageSize.width * (region.x + region.width / 2 - 0.5),
                    y: imageSize.height * (region.y + region.height / 2 - 0.5),
                });
            } else {
                setDummySize(imageSize ?? null);
                setDummyOffset(null);
            }
        } else {
            dummyDoneRef.current = true;
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [originAnim]);
    useEffect(() => {
        if (!dummySrc || !completed) {
            return;
        }
        const timeout = window.setTimeout(() => {
            dummyDoneRef.current = true;
            setDummySrc(null);
        }, 300);
        return () => window.clearTimeout(timeout);
    }, [dummySrc, completed]);
    useEffect(() => {
        if (!dummySrc) {
            return;
        }
        internal.layout.setOuterClass('lg-first-slide-loading', true);
        return () =>
            internal.layout.setOuterClass('lg-first-slide-loading', false);
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [dummySrc]);

    let content: ReactNode = null;
    if (shouldLoad && item && !error) {
        // Plugin slide renderers win (video plugin); undefined passes
        // through to the built-in renderers.
        content = resolvePluginSlideContent(
            internal.plugins,
            item,
            index,
            pluginCtx,
        );
        if (content === undefined) {
            if (slideType === 'image') {
                content = (
                    <ImageSlide
                        item={item}
                        index={index}
                        dummySrc={dummySrc}
                        dummySize={dummySize}
                        dummyOffset={dummyOffset}
                        // v2 appends the real image only once the flight
                        // lands (startAnimationDuration + 100): its fetch
                        // and decode must never jank the flight's frames.
                        deferSrc={
                            !!dummySrc && !!originAnim && !originAnim.closing
                        }
                        onLoad={handleLoad}
                        onError={handleError}
                    />
                );
            } else if (slideType === 'iframe') {
                content = (
                    <IframeSlide
                        item={item}
                        index={index}
                        onLoad={handleLoad}
                    />
                );
            } else {
                // Video items render nothing without the video plugin.
                content = null;
            }
        }
        content = wrapSlideContent(internal.plugins, content, {
            item,
            index,
            isCurrent,
        });
    }

    return (
        <div
            className={cx(
                'lg-item',
                isShown && 'lg-current',
                position === 'prev' && 'lg-prev-slide',
                position === 'next' && 'lg-next-slide',
                inProgress && 'lg-slide-progress',
                shouldLoad && 'lg-loaded',
                completed && 'lg-complete lg-complete_',
                dummySrc && 'lg-first-slide',
                originClasses,
            )}
            style={style}
        >
            {content}
            {error && (
                <span className="lg-error-msg">
                    {settings.strings.mediaLoadingFailed}
                </span>
            )}
            {settings.captionPosition === 'slide' && shouldLoad && item && (
                <div className="lg-sub-html">
                    <CaptionContent item={item} index={index} />
                </div>
            )}
        </div>
    );
}

// packages/angular/src/lib/slide.component.ts
import { NgComponentOutlet } from '@angular/common';
import {
    ChangeDetectionStrategy,
    Component,
    computed,
    DestroyRef,
    effect,
    inject,
    input,
    signal,
    untracked,
    viewChild,
    type TemplateRef,
    type Type,
} from '@angular/core';
import {
    awaitDecode,
    getPreloadIndexes,
    getSlideType,
    type FractionRect,
    type ImageSize,
} from '@lightgallery/headless';

import { LgCaptionContentComponent } from './caption.component';
import { cx } from './cx';
import { LgIframeSlideComponent } from './iframe-slide.component';
import { LgImageSlideComponent } from './image-slide.component';
import { LgGalleryRuntime } from './runtime';
import { LgSlideWrappersComponent } from './slide-wrappers.component';
import { LightGalleryStore } from './store';
import type { LgGalleryItem } from './types';

/**
 * Zoom-from-origin animation state for the opening/closing slide, mirroring
 * the React outlet's `OriginAnimation`:
 * `init`  — slide parked on the trigger rect, no transition classes yet
 * `armed` — transition classes + duration applied, still on the rect
 * `run`   — animating to identity (or back to the rect when closing)
 */
export interface OriginAnimation {
    index: number;
    transform: string;
    /**
     * Fitted image box the flight lands on (capped at the natural size).
     * Absent for a centre close, which has no thumbnail to size against.
     */
    imageSize?: ImageSize;
    stage: 'init' | 'armed' | 'run';
    closing?: boolean;
    /**
     * Closing with no thumbnail to return to (hidden or collapsed trigger,
     * no lgSize): shrink about the stage centre and fade instead.
     */
    toCenter?: boolean;
    /**
     * A feature's flight (origin crop): transforms for the stage boxes
     * around the slides, the part of the image the dummy covers, and the
     * dummy's source when the gallery has none.
     */
    boxes?: { outer: string; inner: string };
    region?: FractionRect;
    dummySrc?: string;
}

/**
 * One `.lg-item` (the host element itself carries the class contract).
 * Content mounts lazily (2.x parity): the current slide loads
 * immediately; neighbors within `preload` load once the current slide's
 * media completes; once loaded, a slide keeps its content for as long as it
 * stays in the DOM window. The vanilla CSS shows the loading spinner until
 * `lg-complete` lands.
 */
@Component({
    selector: 'lg-slide',
    changeDetection: ChangeDetectionStrategy.OnPush,
    imports: [
        LgCaptionContentComponent,
        LgIframeSlideComponent,
        LgImageSlideComponent,
        LgSlideWrappersComponent,
        NgComponentOutlet,
    ],
    host: {
        '[class]': 'hostClasses()',
        '[style.transform]': 'originTransform()',
        '[style.transition-duration]': 'originDuration()',
        '[style.transition-property]': 'originTransitionProperty()',
    },
    template: `
        <ng-template #slideContent>
            @if (renderer(); as rendererCmp) {
            <!-- Feature slide renderer wins (video). -->
            <ng-container
                *ngComponentOutlet="
                    rendererCmp;
                    inputs: rendererInputs();
                    injector: runtime.featureInjector() ?? undefined
                "
            />
            } @else if (slideType() === 'image') {
            <lg-image-slide
                [item]="item()!"
                [index]="index()"
                [dummySrc]="dummySrc()"
                [dummySize]="dummySize()"
                [dummyOffset]="dummyOffset()"
                [deferSrc]="deferSrc()"
                (mediaLoad)="onLoad($event)"
                (mediaError)="onError()"
            />
            } @else if (slideType() === 'iframe') {
            <lg-iframe-slide
                [item]="item()!"
                [index]="index()"
                (mediaLoad)="onLoad()"
            />
            }
            <!-- Video items render nothing without the video feature. -->
        </ng-template>
        @if (renderContent()) {
        <lg-slide-wrappers
            [wrappers]="wrappers()"
            [item]="item()!"
            [index]="index()"
            [isCurrent]="isCurrent()"
            [content]="slideContentTpl()"
        />
        } @if (error()) {
        <span class="lg-error-msg">{{
            runtime.settings().strings.mediaLoadingFailed
        }}</span>
        } @if (captionInSlide()) {
        <div class="lg-sub-html">
            <lg-caption-content [item]="item()" [index]="index()" />
        </div>
        }
    `,
})
export class LgSlideComponent {
    readonly index = input.required<number>();
    readonly item = input<LgGalleryItem | undefined>(undefined);
    /** Which slide carries `lg-current` right now (transition timeline). */
    readonly isShown = input(false);
    /** `lg-prev-slide` / `lg-next-slide` assignment from the timeline. */
    readonly position = input<'prev' | 'next' | undefined>(undefined);
    /** Slide carrying `lg-slide-progress` (outgoing slide). */
    readonly inProgress = input(false);
    readonly originAnim = input<OriginAnimation | null>(null);

    private readonly store = inject(LightGalleryStore);
    protected readonly runtime = inject(LgGalleryRuntime);

    protected readonly error = signal(false);
    private readonly sticky = signal(false);
    private appended = false;

    private readonly slideContentTplQuery =
        viewChild.required<TemplateRef<unknown>>('slideContent');
    protected readonly slideContentTpl = computed(() =>
        this.slideContentTplQuery(),
    );

    protected readonly isCurrent = computed(
        () => this.store.currentIndex() === this.index(),
    );

    /** First feature slide renderer that owns this item wins. */
    protected readonly renderer = computed<Type<unknown> | null>(() => {
        const item = this.item();
        if (!item) {
            return null;
        }
        for (const feature of this.runtime.features()) {
            if (feature.slideRenderer?.canRender(item)) {
                return feature.slideRenderer.component;
            }
        }
        return null;
    });
    protected readonly rendererInputs = computed<Record<string, unknown>>(
        () => ({ item: this.item(), index: this.index() }),
    );
    /** slideWrapper chain, features order = outermost-first (React parity). */
    protected readonly wrappers = computed(() =>
        this.runtime
            .features()
            .map((feature) => feature.slots?.slideWrapper)
            .filter((cmp): cmp is Type<unknown> => !!cmp),
    );
    private readonly completed = computed(
        () => this.store.loadedSlides().has(this.index()) || this.error(),
    );
    private readonly inPreloadRange = computed(
        () =>
            getPreloadIndexes(
                this.store.currentIndex(),
                this.runtime.settings().preload,
                this.store.slidesCount(),
            ).indexOf(this.index()) !== -1,
    );
    protected readonly shouldLoad = computed(() => {
        // Sticky content survives `isOpen` flipping false at close-START:
        // the close flight animates this slide back to the thumbnail,
        // and an open-gated unmount would fly an EMPTY item (invisible
        // close). Teardown belongs to the item's own unmount once the
        // close settles (the phase-gated @for) — the moment 2.x empties
        // `$inner`.
        if (this.sticky()) {
            return true;
        }
        if (!this.store.isOpen()) {
            return false;
        }
        const currentLoaded = this.store
            .loadedSlides()
            .has(this.store.currentIndex());
        return this.isCurrent() || (currentLoaded && this.inPreloadRange());
    });
    protected readonly renderContent = computed(
        () => this.shouldLoad() && !!this.item() && !this.error(),
    );
    protected readonly slideType = computed(() => {
        const item = this.item();
        return item ? getSlideType(item) : 'image';
    });
    protected readonly captionInSlide = computed(
        () =>
            this.runtime.settings().captionPosition === 'slide' &&
            this.shouldLoad() &&
            !!this.item(),
    );

    // 2.x first-slide dummy (`getDummyImageContent`): while the
    // zoom-from-origin flight runs, the trigger's already-decoded
    // thumbnail flies enlarged in place of the still-loading image; the
    // real image mounts only once the flight lands and the dummy drops
    // shortly after the load settles (`loadContentOnFirstSlideLoad`).
    protected readonly dummySrc = signal<string | null>(null);
    protected readonly dummySize = signal<ImageSize | null>(null);
    protected readonly dummyOffset = signal<{ x: number; y: number } | null>(
        null,
    );
    private dummyDone = false;
    private dummyDropTimer: ReturnType<typeof setTimeout> | null = null;
    private destroyed = false;
    /** v2 mounts the real image only once the flight lands. */
    protected readonly deferSrc = computed(() => {
        const anim = this.originAnim();
        return !!this.dummySrc() && !!anim && !anim.closing;
    });

    constructor() {
        // React counterpart: Slide's sticky `shouldLoad` ref — once content
        // mounts it stays for as long as the slide is in the DOM window.
        effect(() => {
            if (this.shouldLoad()) {
                this.sticky.set(true);
            }
        });
        effect(() => {
            const anim = this.originAnim();
            if (
                this.dummyDone ||
                this.dummySrc() ||
                !anim ||
                anim.closing ||
                this.completed() ||
                this.slideType() !== 'image'
            ) {
                return;
            }
            untracked(() => {
                const src =
                    anim.dummySrc ?? this.runtime.getDummySrc(this.index());
                if (!src) {
                    this.dummyDone = true;
                    return;
                }
                this.dummySrc.set(src);
                // A feature's flight may cover only a region of the image
                // with its dummy (a pre-cropped thumbnail file): size and
                // offset the dummy to that region of the fitted box.
                const { imageSize, region } = anim;
                if (imageSize && region) {
                    this.dummySize.set({
                        width: imageSize.width * region.width,
                        height: imageSize.height * region.height,
                    });
                    this.dummyOffset.set({
                        x:
                            imageSize.width *
                            (region.x + region.width / 2 - 0.5),
                        y:
                            imageSize.height *
                            (region.y + region.height / 2 - 0.5),
                    });
                } else {
                    this.dummySize.set(imageSize ?? null);
                    this.dummyOffset.set(null);
                }
                this.runtime.firstSlideLoading.set(true);
            });
        });
        effect(() => {
            if (!this.dummySrc() || !this.completed()) {
                return;
            }
            untracked(() => {
                this.dummyDropTimer = setTimeout(() => {
                    this.dummyDone = true;
                    this.dummySrc.set(null);
                    this.runtime.firstSlideLoading.set(false);
                }, 300);
            });
        });
        inject(DestroyRef).onDestroy(() => {
            this.destroyed = true;
            if (this.dummyDropTimer !== null) {
                clearTimeout(this.dummyDropTimer);
            }
            if (this.dummySrc()) {
                this.runtime.firstSlideLoading.set(false);
            }
        });
        // React counterpart: Slide's afterAppendSlide mount effect (2.x
        // afterAppendSlide fired once when the slide's content mounts).
        effect(() => {
            if (this.shouldLoad() && !this.appended) {
                this.appended = true;
                untracked(() => {
                    const index = this.index();
                    this.runtime.emit('afterAppendSlide', { index });
                    if (this.runtime.settings().captionPosition === 'slide') {
                        this.runtime.emit('afterAppendSubHtml', { index });
                    }
                });
            }
        });
    }

    protected onLoad(event?: Event): void {
        const index = this.index();
        if (this.store.loadedSlides().has(index)) {
            return;
        }
        const isFirstSlide = !this.store.galleryOn();
        const complete = (): void => {
            this.store.dispatch({ type: 'SLIDE_LOADED', index });
            this.runtime.emit('slideItemLoad', {
                index,
                delay: this.loadDelay(isFirstSlide),
                isFirstSlide,
            });
        };
        // Decode gate: `lg-complete` flips only once the browser can
        // paint the FULL image — a loaded-but-undecoded flip paints
        // partially on slow devices. Synchronous when `decode()` is
        // unavailable (the load event already fired); the timeout
        // fallback keeps a stalling decode from stranding the spinner.
        const target = event?.currentTarget ?? event?.target;
        if (
            target instanceof HTMLImageElement &&
            typeof target.decode === 'function'
        ) {
            void awaitDecode(target).then(() => {
                if (!this.destroyed) {
                    complete();
                }
            });
            return;
        }
        complete();
    }

    private loadDelay(isFirstSlide: boolean): number {
        const settings = this.runtime.settings();
        return isFirstSlide
            ? (settings.zoomFromOrigin
                  ? settings.startAnimationDuration
                  : settings.backdropDuration) + 10
            : 0;
    }

    protected onError(): void {
        const index = this.index();
        if (this.store.loadedSlides().has(index)) {
            return;
        }
        this.error.set(true);
        const isFirstSlide = !this.store.galleryOn();
        this.store.dispatch({ type: 'SLIDE_ERROR', index });
        // A failed load settles the slide too (2.x fires slideItemLoad on
        // error): the error message is on screen, neighbours may preload
        // and the slideshow moves on instead of waiting forever.
        this.runtime.emit('slideItemLoad', {
            index,
            delay: this.loadDelay(isFirstSlide),
            isFirstSlide,
        });
    }

    protected readonly hostClasses = computed(() =>
        cx(
            'lg-item',
            this.isShown() && 'lg-current',
            this.position() === 'prev' && 'lg-prev-slide',
            this.position() === 'next' && 'lg-next-slide',
            this.inProgress() && 'lg-slide-progress',
            this.shouldLoad() && 'lg-loaded',
            this.completed() && 'lg-complete lg-complete_',
            !!this.dummySrc() && 'lg-first-slide',
            this.originClasses(),
        ),
    );

    protected readonly originTransform = computed(() => {
        const anim = this.originAnim();
        if (!anim) {
            return null;
        }
        if (anim.stage === 'init') {
            return anim.transform;
        }
        return anim.stage === 'run' && !anim.closing
            ? 'translate3d(0, 0, 0)'
            : anim.transform;
    });

    protected readonly originDuration = computed(() => {
        const anim = this.originAnim();
        return anim && anim.stage !== 'init'
            ? `${this.runtime.settings().startAnimationDuration}ms`
            : null;
    });

    // The origin transform must LAND, never animate: measuring
    // (computeOrigin) forces a recalc that baselines the item at
    // identity, and the `:not(.lg-start-end-progress)` inherit rule
    // would transition identity → origin — a visible
    // fullscreen→thumbnail shrink before the flight.
    protected readonly originTransitionProperty = computed(() => {
        const anim = this.originAnim();
        return anim && anim.stage === 'init' ? 'none' : null;
    });

    private readonly originClasses = computed(() => {
        const anim = this.originAnim();
        if (!anim || anim.stage === 'init') {
            return false as const;
        }
        return anim.closing
            ? 'lg-start-end-progress'
            : 'lg-start-progress lg-start-end-progress';
    });
}
