// packages/angular/plugins/pager/index.ts
import {
    ChangeDetectionStrategy,
    Component,
    computed,
    DestroyRef,
    inject,
    signal,
} from '@angular/core';
import { LG_PLUGIN_CONTEXT, type LgFeature } from '@lightgallery/angular';

/** Pager feature (2.x `lg-pager`): dot navigation with thumb popovers. */

export interface PagerSettings {
    /** Enable the pager. */
    pager: boolean;
}

export const pagerSettings: PagerSettings = {
    pager: true,
};

@Component({
    selector: 'lg-pager-list',
    changeDetection: ChangeDetectionStrategy.OnPush,
    template: `
        @if (settings().pager) {
            <div
                class="lg-pager-outer"
                [class.lg-pager-hover]="hover()"
                (mouseover)="onMouseOver()"
                (mouseout)="onMouseOut()"
            >
                @for (item of ctx.items(); track $index) {
                    <span
                        class="lg-pager-cont"
                        [class.lg-pager-active]="$index === currentIndex()"
                        role="button"
                        tabindex="0"
                        [attr.data-lg-item-id]="$index"
                        [attr.aria-label]="'Go to slide ' + ($index + 1)"
                        [attr.aria-current]="$index === currentIndex()"
                        (click)="ctx.actions.goToSlide($index)"
                        (keydown)="onKeydown($event, $index)"
                    >
                        <span class="lg-pager"></span>
                        <div class="lg-pager-thumb-cont">
                            <span class="lg-caret"></span>
                            <img
                                [attr.src]="item.thumb ?? null"
                                [alt]="item.alt ?? ''"
                            />
                        </div>
                    </span>
                }
            </div>
        }
    `,
})
export class LgPagerListComponent {
    protected readonly ctx = inject(LG_PLUGIN_CONTEXT);
    protected readonly settings = computed(
        () => this.ctx.settings() as unknown as PagerSettings,
    );
    protected readonly currentIndex = computed(
        () => this.ctx.state().currentIndex,
    );
    protected readonly hover = signal(false);
    private hoverTimer: ReturnType<typeof setTimeout> | null = null;

    constructor() {
        inject(DestroyRef).onDestroy(() => {
            if (this.hoverTimer !== null) {
                clearTimeout(this.hoverTimer);
            }
        });
    }

    protected onMouseOver(): void {
        if (this.hoverTimer !== null) {
            clearTimeout(this.hoverTimer);
            this.hoverTimer = null;
        }
        this.hover.set(true);
    }

    protected onMouseOut(): void {
        this.hoverTimer = setTimeout(() => this.hover.set(false), 0);
    }

    protected onKeydown(event: KeyboardEvent, index: number): void {
        if (event.key === 'Enter' || event.key === ' ') {
            event.preventDefault();
            this.ctx.actions.goToSlide(index);
        }
    }
}

export function withPager(
    options: Partial<PagerSettings> = {},
): LgFeature<PagerSettings> {
    return {
        name: 'pager',
        defaults: pagerSettings,
        options,
        slots: {
            components: LgPagerListComponent,
        },
    };
}

// packages/react/src/plugins/pager/index.tsx
import { useRef, useState, type ReactElement } from 'react';

import { cx } from '../../cx';
import {
    useGalleryActions,
    useGalleryInternal,
    useGalleryState,
} from '../../context';
import { usePluginSettings } from '../runtime';
import type { LgPlugin } from '../types';

/** Pager plugin (2.x `lg-pager`): dot navigation with thumb popovers. */

export interface PagerSettings {
    /** Enable the pager. */
    pager: boolean;
}

export const pagerSettings: PagerSettings = {
    pager: true,
};

function PagerList(): ReactElement | null {
    const state = useGalleryState();
    const actions = useGalleryActions();
    const internal = useGalleryInternal();
    const settings = usePluginSettings<PagerSettings>();
    const [hover, setHover] = useState(false);
    const hoverTimerRef = useRef<number | undefined>(undefined);

    if (!settings.pager) {
        return null;
    }

    return (
        <div
            className={cx('lg-pager-outer', hover && 'lg-pager-hover')}
            onMouseOver={() => {
                window.clearTimeout(hoverTimerRef.current);
                setHover(true);
            }}
            onMouseOut={() => {
                hoverTimerRef.current = window.setTimeout(
                    () => setHover(false),
                    0,
                );
            }}
        >
            {internal.items.map((item, index) => (
                <span
                    key={index}
                    data-lg-item-id={index}
                    className={cx(
                        'lg-pager-cont',
                        index === state.currentIndex && 'lg-pager-active',
                    )}
                    role="button"
                    tabIndex={0}
                    aria-label={`Go to slide ${index + 1}`}
                    aria-current={index === state.currentIndex}
                    onKeyDown={(event) => {
                        if (event.key === 'Enter' || event.key === ' ') {
                            event.preventDefault();
                            actions.goToSlide(index);
                        }
                    }}
                    onClick={() => actions.goToSlide(index)}
                >
                    <span className="lg-pager" />
                    <div className="lg-pager-thumb-cont">
                        <span className="lg-caret" />
                        <img src={item.thumb} alt={item.alt ?? ''} />
                    </div>
                </span>
            ))}
        </div>
    );
}

const Pager: LgPlugin<PagerSettings> = {
    name: 'pager',
    defaults: pagerSettings,
    slots: {
        components: PagerList,
    },
};

declare module '../../types' {
    interface LightGalleryPluginSettings {
        pager: Partial<PagerSettings>;
    }
}

export default Pager;
